package.json
src/notifier.js

This adds the same fix as in `shim.js` to prevent the wrap function to crash when running with selenium.
Also, I updated `package.json` based on #116 to allow the build in travis to run correctly.

Fix selenium issues

---

.travis.yml
travis.yml

- remove misnamed `travis.yml` file
- add `sudo: false` to the correct file
cc @coryvirok

TravisCI config fixes

---

docs/plugins.md

Fix jquery plugin docs

---

src/notifier.js

Bug found by @joker-777. Big thanks!

Fix jQuery ignoreAjaxErrors.

---

README.md

Remove broken FAQ link

---

src/notifier.js
test/notifier.test.js

Addresses https://github.com/rollbar/rollbar.js/issues/188 and adds related test.

Add support for arrays as a custom data argument to Rollbar log methods

---

README.md
docs/api.md
docs/configuration.md
package.json
src/globalnotifier.js
src/notifier.js
src/shim.js
test/notifier.test.js
test/rollbar.test.js
test/shim.test.js

This is the rollbar.js side of https://github.com/rollbar/node_rollbar/issues/61
Closed previous pull due to needing to fix the rebase off master.
Addressed @coryvirok 's remarks (unfortunately I can't carry them over here), and added more tests.  
Going to add docs and examples next.

Promise rejection handler

---

README.md
docs/extension-exceptions.md
examples/extension-exceptions/test.html

@coryvirok @brianr 
This addresses [Issue 182](https://github.com/rollbar/rollbar.js/issues/182) by adding an example an a related doc file.  Let me know of any improvements you'd like to see!

Adding example and documentation related to adblockers

---

docs/extension-exceptions.md

Sorry, I used to be an editor for my HS newspaper :/

Changed function names from Add to Ad in ad-blocker example

---

examples/bower/index.html

Added some options to verify they work, and added the missing function, so the example works out of the box after adding an ACCES_TOKEN

added additional options to the bower example, for Issue #173

---

Gruntfile.js
examples/requirejs/README.md

@coryvirok I figured this might be helpful

Update package version in requirejs example README

---

package.json

added some missing development dependencies, #238

---

package.json

I updated to v0.2.3 of console-polyfill which contains a fix for the problem mentioned in #204.

updated console-polyfill to get the latest fixes

---

src/util.js

Changes as discussed in https://github.com/rollbar/rollbar.js/pull/249

Invoke console methods with right this-context

---

.eslintignore
.eslintrc
.gitignore
package.json
src/browser/bundles/rollbar.snippet.js
src/browser/logger.js
src/browser/predicates.js
src/browser/rollbar.js
src/browser/shim.js
src/browser/snippet_callback.js
src/browser/transforms.js
src/browser/transport.js
src/queue.js
src/rollbar.js
src/server/logger.js
src/server/parser.js
src/server/rollbar.js
src/server/transforms.js
src/server/transport.js
src/utility.js

@rokob - there are still some outstanding issues that eslint is reporting
and they look like they're more than just style changes. Can you take a look?
```
vagrant@devbox:~/www/rollbar.js$ eslint -f stylish src/
/home/vagrant/www/rollbar.js/src/apiUtility.js
51:7  error  'path' is already defined  no-redeclare
/home/vagrant/www/rollbar.js/src/browser/bundles/rollbar.js
2:5  error  'globals' is assigned a value but never used  no-unused-vars
/home/vagrant/www/rollbar.js/src/browser/logger.js
44:13  error  'RollbarJSON' is not defined  no-undef
/home/vagrant/www/rollbar.js/src/server/transforms.js
174:33  error  'options' is defined but never used  no-unused-vars
✖ 4 problems (4 errors, 0 warnings)
```

Fixes issue #266 and applied eslint recommended defaults

---

src/server/rollbar.js

Without this change, environment always reported as development.

Actually honor NODE_ENV

---

src/server/rollbar.js
src/server/transforms.js
test/server.transforms.test.js

handle messages and errors on the server side

---

package.json

See: https://snyk.io/vuln/npm:ms:20170412

debug@2.6.8 to fix ReDoS vulnerability in ms<2.0.0

---

src/server/transforms.js
test/server.transforms.test.js

we were not including the payload options in the final payload on the server side, fix that

Properly include payload options in final payload on server

---

README.md

@rokob wanna merge this if it looks correct to you?

remove payload.data from readme

---

src/browser/rollbar.js
src/rateLimiter.js
src/rollbar.js
src/server/rollbar.js
test/rateLimiter.test.js

fix the rate limiter payload

---

src/browser/transforms.js
src/server/transforms.js
test/server.transforms.test.js

Match what we allow on the browser on the server

[Fix #323] fix getting environment from the payload object

---

index.d.ts

fix syntax errors in typescript

---

src/browser/transforms.js

actually pass the generated uuid along with the payload

---

README.md

Reverts rollbar/rollbar.js#354 since I'm having issues getting the docs to update properly in prod

Revert "Adding Segment info to README"

---

README.md

Reverts rollbar/rollbar.js#356

Revert "document nojson dist for CSP"

---

README.md
src/browser/rollbar.js
src/rollbar.js
src/server/rollbar.js
test/browser.rollbar.test.js

add an optional second parameter to configure

---

index.d.ts

add some missing configuration properties, make them optional for reconfig

---

src/utility.js
test/utility.test.js

make scrubbing handle self-referential objects

---

package.json
src/utility.js

Use lodash is native function checking for JSON.* functions

---

src/browser/rollbar.js
src/browser/telemetry.js
src/rollbar.js
src/telemetry.js
test/telemetry.test.js

Fixes #394 
This isn't quite done yet, but wanted to get this started.

allow the telemetry stuff to be reconfigured

---

src/browser/telemetry.js

This implements two possible additional scrubbing hooks for telemetry data:
1. Scrub all input values
2. A function which takes a description of a dom node and returns true if we should scrub the value
The first option, either scrub all values or only password fields, is the easiest to implement, is
the most straight forward, and will definitely allow people to ensure they do not leak data.
The second option, is more complicated to use but allows for maximum flexibility, it subsumes the
first option actually by just using a function that always returns true. The structure that
describes the dom node is:
```
{
tagName,
id,
classes,
attributes
}
```
It is an internal structure used to generate the string representation of an element that we embed
in the telemetry event. This allows people …

[WIP] Scrubbing for telemetry

---

src/browser/predicates.js
test/browser.predicates.test.js

fix blacklist

---

src/utility.js
test/utility.test.js

A version of #403 without using lodash so theres no shim protection.

Use json polyfil if non native

---

src/browser/shim.js
src/browser/telemetry.js

if enabled is false then set all instrumentation to false

---

index.d.ts
package.json

add lambdaHandler to typings

---

src/browser/domUtility.js
src/browser/telemetry.js
test/browser.domUtility.test.js

move the dom description stuff out of browser/telemetry to test it, fix how the truncation works
fixes #430

refactor the dom telemetry description stuff

---

src/server/rollbar.js

maxItems only makes sense in the browser, ignore it on the server

---

webpack.config.js

fix the umd build to not pollute the global namespace

---

src/transforms.js

need to propagate the originalArgs for checkIgnore to work

---

package.json

https://nodesecurity.io/advisories/534

Update debug package to v2.6.9 to address Node Security Warning

---

examples/universal-browser/server.js
src/rateLimiter.js
src/rollbar.js

Working out the kinks in the way maxItems is handled throughout the lifecycle of the notifier.

Fix global config

---

src/rollbar.js

Call callback even if logging same as last error

---

src/react-native/transforms.js

Some things to get source maps working

rewrite ios bundle filenames

---

README.md

Fixed code formatting with correct ticks in README

---

src/browser/errorParser.js
src/browser/transforms.js

if we would end up with no frames, include extra raw stack info

---

src/browser/errorParser.js
src/browser/predicates.js

handle malformed errors, mostly for IE

---

README.md

instructions about how to upgrade browserjs installations

---

webpack.config.js

turn sourceMaps on for uglify

---

README.md

Adding in testing docs for Firefox

---

index.d.ts

add transform and checkIgnore to configuration type

---

README.md
index.d.ts
src/browser/telemetry.js
src/telemetry.js

Fixes #454 
Fixes #444 
This is a bit of a work in progress. I took one approach to this because the feature request is a bit vague. I understand the desire for headers, but including the body I think it is an anti-pattern. Nonetheless this is what supporting it would look like.

Add support for capturing more information from network requests

---

src/server/logger.js

Fixes #526
Replace calls to bind with function application.

Do not bind the console in the custom logger

---

src/apiUtility.js

Make sure context becomes a string if it exists and is not already one

---

README.md
examples/universal-node/other.js
examples/universal-node/server.js
src/server/logger.js
src/server/rollbar.js

make the verbose option turn on/off all logging

---

README.md
index.d.ts
src/browser/rollbar.js
src/browser/transforms.js
src/server/rollbar.js
src/server/transforms.js
src/utility.js
test/server.transforms.test.js
test/utility.test.js

This PR addresses what user data to collect by default, and provides configuration mechanisms for fine grained control over deciding what to collect (or not).
Fixes #604 
Fixes #605 
Fixes #606

Modify what user data is collected by default

---

README.md
index.d.ts
src/react-native/transforms.js
src/server/transforms.js

Support code_version and codeVersion at the top level of configuration

---

index.d.ts

add typings for the express error handler helper

---

src/browser/transforms.js

Be super extra careful about accessing exception properties

---

src/rollbar.js

Fixes #486 
Some rogue scripts can cause identical errors to occur, we were not actually coalescing these properly, this fixes that.

Ignore last error for real

---

index.d.ts
src/server/rollbar.js

Report lambda timeouts 1 second before they happen

---

src/browser/globalSetup.js

Properly call the existing onerror handler if set

---

index.d.ts
src/browser/errorParser.js
src/browser/globalSetup.js
src/react-native/transforms.js
src/react-native/transport.js
src/rollbar.js
src/utility.js
webpack.config.js

Add maxTelemetryEvents to types and clean up a bunch of nits

---

src/server/rollbar.js

Handle async lambda functions better

---

index.d.ts

chore: Add wait type def

---

src/predicates.js
test/predicates.test.js

Previously hostWhiteList/hostBlackList were only compared to `trace` in the payload, not `trace_chain`.

Apply hostWhiteList/hostBlackList to trace_chain

---

examples/no-conflict/package.json
examples/universal-node/package.json

Responding to warnings at /network/alerts.

Bump dep versions in examples

---

src/utility.js
test/browser.rollbar.test.js

Fixes: https://github.com/rollbar/rollbar.js/issues/783

CaptureEvent should handle ambiguous args

---

.travis.yml
package-lock.json
package.json

Fixes: https://github.com/rollbar/rollbar.js/issues/805

Enable node 12

---

src/browser/rollbar.js

fix: gracefully handle loadFull being called multiple times

---

package-lock.json
package.json

Related: https://github.com/rollbar/rollbar.js/pull/820

Remove dev dependency grunt-tagrelease

---

.github/workflows/workflow.yml

Format --cache-control option so that s3 sync will accept it.

Cache-control arg formatting

---

src/browser/telemetry.js
test/browser.rollbar.test.js

This PR ensures stacks for reporting xhr and fetch errors are built only when that feature is enabled.
Calling `stack()` on an Error object causes it to show up at `Error.prepareStackTrace`. That's unavoidable, but limiting it as much as possible helps the anonymous errors feature (which relies on `Error.prepareStackTrace`) work more reliably in more situations.

Only build stack for http errors when the feature is enabled

---

package-lock.json
package.json
src/server/sourceMap/stackTrace.js

Fixes: https://github.com/rollbar/rollbar.js/issues/862

Remove buffer-from and use node's Buffer.from

---

src/browser/telemetry.js

The spec for `XMLHttpRequest` requires `open()` to be called before `setRequestHeader()`, however `open()` may be called async and in that case Rollbar's handler for `setRequestHeader()` may execute first.
This PR refactors the initialization for both `open()` and `setRequestHeader()` to make async open safe in all cases.
**Testing**
The existing tests already use async open, but the actual execution order is browser dependent. This error and the fix have been tested manually with a browser (Chrome 73) and app that exercise the condition.

Make setRequestHeader safe after async open

---

index.d.ts

This PR adds missing field `scrubPaths` to `Configuration` interface in TS typings.
> Description here
> Allow scrubbing by full path in payload [#869](https://github.com/rollbar/rollbar.js/pull/869)

Adds 'scrubPaths' to Configuration interface

---

.github/workflows/ci.yml
Gruntfile.js
README.md

Update the CI badge in the README to work with Github CI.
This has been tested with a test version tag, however the badge will remain inactive on master until the next version release tag is pushed.

Update CI badge from travis to github CI

---

README.md

Update badge URL to use `tag=latest`

Update badge to use tag=latest

---

index.d.ts

It seems to me that this was forgotten in [#903](https://github.com/rollbar/rollbar.js/pull/903/files#diff-681622c5abec143b2ec6b3b083f1981d27a08b970c149263fb60dbddc7939733R19-R20) (/Cc @waltjones), apologies if I missed something instead.
_Those changes were made in the GitHub editor, not a local environment, so we'll see what CI says..._
- N/A The code changed/added as part of this pull request has been covered with tests
- N/A All tests related to the changed code pass in development

Add TypeScript definitions for CSP error reporting

---

package-lock.json
package.json
src/server/rollbar.js
src/server/telemetry.js
src/server/telemetry/urlHelpers.js
test/server.telemetry.test.js

Enables telemetry in Node.js for logging and http(s) request.
**Logging:** 
* Hooks `process.stdout` and `process.stderr`.
* Records the log string and log level.
**Network:**
* Hooks `http.request` and `https.request`.
* Network capture records method/verb, url, status code, start/end time in ms.
* Non-HTTP network errors (connection errors, DNS errors, etc.) are recorded.
* When header capture is enabled, headers are scrubbed based on `scrubHeaders` settings. 
**Config options are consistent with browser js telemetry options:**
```
{
autoInstrument: true // enable logging and network capture, without network headers
}
```
```
{
autoInstrument: {
network: true, // enable/disable network and log capture independently
log: true 
}
```
```
{
autoInstrument: {
network: true, …
```

Node.js telemetry - logging and http(s) request

---

.github/workflows/ci.yml
test/server.transforms.test.js

Updating node versions in the CI matrix.
This PR also updates a test case to be Node 16 compatible.
ch85326

Add node 14, 16 to ci

---

src/browser/telemetry.js
test/browser.rollbar.test.js

Reverts rollbar/rollbar.js#1001

Revert "Prevent error when fetch response has empty body"

---

package-lock.json
test/browser.rollbar.test.js

CI started failing sometime after the last PR. There were two issues, fixed in this PR:
* Node tests needed an updated fsevents dependency.
* Some browser tests are updated for handling async occurrence sending. (See here for the original change: https://github.com/rollbar/rollbar.js/pull/1037)
Fixes SC #115474

Fix CI issues

---

src/browser/transport/fetch.js

This PR removes arrow functions that aren't compatible with IE11 and some other browsers. (The Rollbar.js build process currently doesn't include a transpile step that would make this compatible.)
Fixes https://github.com/rollbar/rollbar.js/issues/1064
https://app.shortcut.com/rollbar/story/120517

Remove arrow functions in browser target

---

package.json

Improve search ranking on npmjs and maybe google
- Fix [SC-]
- Fix #1

Add keywords and more detailed description to package.json

---

src/browser/transport.js

In this commit, we prevent coupling the Zone check to Angular, as zone.js can be used with any framework. We always ensure that we get the root zone and run the callback within it.

perf: make Zone check framework agnostic

---

src/browser/core.js
src/browser/rollbar.js
src/tracing/context.js
src/tracing/contextManager.js
src/tracing/exporter.js
src/tracing/session.js
src/tracing/span.js
src/tracing/spanProcessor.js
src/tracing/tracer.js
src/tracing/tracing.js

Adds OTel compatible tracing support. This implementation aims to be lightweight and simple to use in browser applications that don't want to pull in all of the opentelelemetry-js packages.
* This PR adds trace, span, and context management.
* Exporter will com in a follow up PR.
* Tests will com in a follow up PR.

Sessions and tracing

---

src/tracing/span.js
src/tracing/spanProcessor.js
test/tracing/contextManager.test.js
test/tracing/span.test.js
test/tracing/spanProcessor.test.js
test/tracing/tracing.test.js

Adds initial tests for tracing. This PR also includes a couple of light refactors related to the tests.

Initial tests for tracing

---

.cursor/rules/rollbar-js-guidelines.md
.github/copilot-instructions.md
.gitignore
CLAUDE.md

The changes primarily involved updating documentation across multiple files to include information about:
- Session replay capabilities
- Tracing infrastructure details
- Modern development environment specifications
- Additional coding standards
- Part of [CAT-353/rrweb-integration](https://linear.app/rollbar-inc/issue/CAT-353/rrweb-integration)

rrweb: Update documentation to include session replay and tracing features

---

src/server/rollbar.js

Server: Fix unhandled errors so that they are logged at `uncaughtErrorLevel`.

server: use uncaughtErrorLevel

---

src/browser/core.js
src/react-native/rollbar.js
src/rollbar.js
src/server/rollbar.js
src/tracing/exporter.js
test/tracing/exporter.toPayload.test.js

Enable ReplayMap

---

examples/angular/package-lock.json

Upgraded various dependencies in the angular example using `npm upgrade`.
n/a

Upgrade dependencies for angular example

---

src/browser/core.js
test/browser.core.test.js

Use 'rollbar' prefix on Rollbar attributes.
- [d] Bug fix (non-breaking change that fixes an issue)

Prefix rollbar attributes

---

src/telemetry.js
test/browser.telemetry.test.js

`rate` is more intuitive in this context.

Rename ratio -> rate

---

src/browser/shim.js
src/browser/transport/xhr.js
src/logger.js

Resolve eslint warnings that are failing CI.

Resolve eslint warnings
