rollbar/rollbar.js

- src/notifier.js
Using a repeating timer to call Notifier.processPayloads every second is unnecessary. The error reporting queue can be notified when there is data present and schedule time to send data to the remote server instead of polling to see if there is data. The processing of error payloads is left async using setTimeout to avoid doing a large amount of work right when reporting an error and allows for batching.
> Remove the 1s repeating timer that processed the error queue

- src/error_parser.js
The minified version of the buggy function is this:
```javascript
function o(n) {
function e() {
var e = [];
try {
e = l.parse(n)
} catch (t) {
e = []
}
for (var r = [], s = 0; s < e.length; s++) r.push(new a(e[s]));
return r
}
return {
stack: e(),
message: n.message,
name: n.name
}
}
```
> Change argument name in Stack() to fix uglify bug.

- src/notifier.js
I've removed the `else if` and use return inside the `if` statement,
since I think now is very clear the concept of `immediate`.
> Remove unneed else if. @brianr.

- src/globalnotifier.js
- src/shim.js
This prevents the shim to send reports when full notifier is already loaded.
> Don't call shim's onerror and use the original one.

- src/notifier.js
When a Subclass of Error or any other object with a stack is provided with rollbar it is understood as the error argument.
Then the stack is read from it and made available with the respective rollbar item.
This fix what I have seen at #63.
> Recognise of objects with stack property as error

- src/shim.js
Hi!
I noticed that your CloudFront hosted snippet has `Access-Control-Allow-Origin: *` set.
It would be nice to load the full code with crossorigin attribute as then any runtime or syntax errors inside Rollbar.js get properly reported.
Blank string means `anonymous`.
More at https://bugsnag.com/blog/script-error
> Load full source with crossOrigin

- package.json
For some people installing dependencies with git:// protocol is blocked. This is making it a little easier.
> Make npm install easier for git:// dependencies

- src/notifier.js
- src/xhr.js
- test/notifier_retry.test.js
This is a first run at fixing #107. If a payload fails to be delivered to Rollbar because of something that's likely to be a network failure (a response back without any status code, or a network timeout) then the payload is put back on queue 10 seconds later to be retried.
This is a first run to scope this out and start some discussion. There's a good few debatable points here:
- What should happen with the callback for the event that's being logged? Currently I've opted to be maximally backward compatible: it fires on the first error, exactly as now, and future retries never trigger it, whether they're successful or not.
- The retry delay should presumably be configurable? Should it be disableable?
- Should we eventually stop retrying?
- Should this be some sort of exponential backoff …
> Retry events that failed to send due to network failures

- bower.json
I also removed the Browserstack files from Bower since they are only used during development/testing.
> Re-add snippet for Bower distribution

- README.md
A user emailed us to let us know that he thinks this flag should be set to true and not false in our quickstart docs: "I think the simplest way to get someone started quickly and on the right foot with Rollbar would be to make the `captureUnhandledRejections` option set to `true` in your first quick start snippet. That way, the developer using Rollbar will see all errors from the get-go instead of mistakenly assuming their app is having no issues because nothing is showing up on Rollbar, and they can pare back their settings if they're getting overwhelmed by one type of request."
I agreed with him. Hopefully you do too 😸
> Update captureUnhandledRejections in Quickstart docs

- README.md
It seems that cloudflare support the restrictions by the iOS9 webviews,
so we can remove this section.
> Remove iOS9 instructions for SSL issues

- .npmignore
I created a `.npmignore` file which is a clone of `.gitignore` but with the `release` folder added.  This will make it so the `release` folder is not included in future builds.
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package
> ignore the release folder when building the package, #215

- src/notifier.js
- test/notifier.test.js
In response to issue #236, this patch makes the log functions return an object containing the generated UUID so it can be used, even before the callback returns.
> return uuid from log functions, #236

- .gitmodules
Fixes #132.  We had a legacy reference to TraceKit, but we haven't been using it since v1.3.0
> remove a remnant from our old usage of TraceKit

- src/util.js
Fixes #205 even though there is a separate old PR which also does some fixing, this is the minimal change to get things working. There is a higher order question about a better fix not to rely on Object.create, but in the meantime to alleviate some pain this is more straightforward.
> [Fixes #205] add Object.create polyfill for IE8

- src/notifier.js
- test/notifier.test.js
This adds support for getting more context, even when the rejection error itself is null. Without it, there is no information to go on.
> Retain more of the context on null rejections

- package.json
- src/browser.js
- src/notifier.js
- src/util.js
- src/xhr.js
- test/util.test.js
Addresses #128 by providing a customized console.log/error/info renderer to prevent the dreaded `[object Object]` by rendering JSON instead.
> log out json for objects in IE8 and below

- package.json
- test/server.transforms.test.js
Hey ☺️,
with the latest version having a request object without a headers key fails (even though that's allowed according to the docs). This can be solved by just updating `request-ip` to the latest version. I also added a new test that will check that using an empty request object will not fail.
Thank you for your great product by the way, it's very helpful for us at greenkeeper ✨
> Do not fail if the request object does not have a headers key (update request-ip)

- README.md
- src/server/rollbar.js
- test/server.rollbar.test.js
this ports the client param handling over to the server side. the only real difference is attempting to identify a `request` object. the first object found that contains at least one of the optional `request` keys is considered to be a request (this may result in false positives - we could require more than one? a minimal subset? ). otherwise the logic is identical.
i added tests to verify all the old parameter ordering still worked, and i added a single test for unordered params. i couldn't figure out how to metaprogram tests in `vows`, otherwise i would have tested for every combination.
> [#282] handle unordered params on the server side

- .npmignore
These don't add a lot of value inside of a published tarball. This should shave ~1.5Mb from the installed package
> Remove examples and coverage from published package

- src/browser/rollbar.js
- src/browser/shim.js
- src/server/parser.js
- src/server/transforms.js
- src/utility.js
Sometimes people use `Object.create(null)` which means that Object does not end up in the prototype chain of said created objects. This means that hasOwnProperty is not a method on that object so calling `obj.hasOwnProperty(prop)` will break. To get around this, we can use `Object.prototype.hasOwnProperty.call(obj, prop)`. As far as I can tell this is safe at least as far back as IE 6 and all version of node. It is only relevant when we don't really know how the object was constructed, so it isn't necessary to use this universally. There is a miniscule performance hit and a bit of a readability issue with it, so prefer not to use this style when we create the object ourselves.
> Fixes #290 handle objects without Object in prototype chain

- src/utility.js
- test/utility.test.js
this fixes it as long as the prototype chain is correct
> subclasses of errors were not treated as errors before

- package.json
Fixes #277
`console-polyfill` 0.3.0 is out on npmjs now, which has the fix that was contained in the rollbar fork.
> Moving back to the upstream version of console-polyfill

- src/browser/rollbar.js
Rejecting with a non-error reason results in `reason.message` or `String(reason)` being set as the message to log. This gets rids of structure that the reason object might have had, so include the reason again to be picked up in custom data. I am not sure I would call it an anti-pattern per se to use non-errors as reasons for rejecting promises, but it is highly non-standard.
> Unhandled rejections [Fixes #307]

- src/browser/rollbar.js
- src/queue.js
- src/rollbar.js
- src/server/rollbar.js
- test/queue.test.js
As far as I can tell, all the verbose option used to do was log to console.error when we are about to log an exception, so this adds that functionality back
> add back verbose logging

- src/browser/rollbar.js
- src/server/rollbar.js
- test/browser.rollbar.test.js
We added a singleton helper to the server side, it is something people have been confused about and asked for on the browser side. This is what it would look like.
> Browser singleton

- .gitignore
- src/browser/rollbar.js
- src/rollbar.js
- src/server/rollbar.js
- test/browser.rollbar.test.js
- test/server.rollbar.test.js
`lastError` used to be a property that was stored on the notifier instance, this was used for a very simple form of deduping of errors; add this functionality back.
> add back lastError on the rollbar instance

- src/browser/predicates.js
- test/browser.predicates.test.js
We have a hostWhiteList option, this implements the alternative blacklist which allows you to ignore errors which have any frame in their backtrace with a "filename" that matches a regex in this list.
> add a blacklist option to the browser side [Fixes #283]

- src/server/rollbar.js
See #262. This adds a `wrapCallback` helper for the server side to automatically report errors returned to callback to Rollbar.
> [#262] add a helper for wrapping callbacks

- README.md
- src/notifier.js
- src/queue.js
- test/queue.test.js
The queue gets the item to log that represents the data in the final payload structure of
```
{
"access_token": "abc123",
"data": { ... }
}
```
rather than the whole payload itself. The API object is responsible for wrapping that data object up
inside a structure like the above and then sending it. Thus the body of the item is a top level key
rather than nested under the data key.
Secondly, everyone wants the original error to be output if there is one isntead of just the
exception message, so make it so.
> Fix #331 Verbose logging was using the wrong key structure

- src/browser/rollbar.js
- src/browser/transforms.js
- src/server/rollbar.js
- src/server/transforms.js
- src/transforms.js
- test/browser.transforms.test.js
- test/server.transforms.test.js
- test/transforms.test.js
Include message if we have one even if we also have a stack trace
> [Fixes #336] Propagate message

- src/browser/globalSetup.js
- src/browser/rollbar.js
- src/browser/shim.js
- src/browser/transforms.js
We wrap certain built-ins in the browser and rethrow exceptions. When such an error occurs, our wrapper ends up in the stack trace because technically it is running, but it isn't really part of the error so there is no reason for it to be in the stack trace.
There are a few different ways I looked at fixing this, but in the end just checking for our `f._wrapped` method signature in the frame is the simplest and actually works about as well as any other approach. Threading state around is a bit of a mess, and actually munging the exception at the rethrow site is impossible due to browser differences.
> [Fixes #269] get rid of rollbar wrapper stack frames

- src/queue.js
- src/server/rollbar.js
It is possible that calling wait does not actually keep the event loop spinning while all events are processing. The proper use of interval timers in the queue will keep things open until all the pending requests have actually gone out.
> add some intervals to keep the event loop running when wait is called

- README.md
- src/browser/rollbar.js
- src/server/rollbar.js
The configuration options for capturing unhandled exceptions and rejections should be the same on the browser and server
> unify configuration options

- src/rollbar.js
- src/server/transforms.js
- src/utility.js
fix one case where we might have called the callback twice which could cause odd behaviour
> Address issue with handleItemWithError possible not calling the callback

- src/server/transforms.js
- test/server.transforms.test.js
Allow more flexibility in the type of request objects we can handle on the server side. Specifically, handle the type of requests that hapi.js creates
> Allow more flexibility of request objects

- index.d.ts
> first pass at a typescript declaration file

- index.d.ts
This seems like it was accidentally left out of the typescript definition?
> Add accessToken to typescript configuration interface

- examples/universal-browser/test.html
- src/browser/telemetry.js
The third argument to replace is a function that is required to return a function which becomes the new function for a given property on an object. If you don't return a function then the property on the object gets replaced with undefined, breaking everything.
This only manifests if onreadystatechange is defined on an xhr request, which was not something I did during manual or automated testing. I added it to the manual test page and verified that before this diff things were broken, and afterwards everything works as expected.
> fix telemetry network bug

- src/utility.js
Fixes #388 
If `Date.now()` returns `new Date()` which is what Date.js does for some crazy reason, then `+Date.now()` is the same as `+new Date()` which is the same fallback we have when `Date.now` is undefined. Otherwise, if `Date.now()` returns a timestamp like it should, then `+Date.now()` is just the same as `Date.now()` through the magic of Javascript operators.
> no matter what Date.now() returns, make it a number

- README.md
The `<head>` tag is not currently viewable in the README
> Fix `<head>` tag in README

- src/browser/predicates.js
- src/browser/rollbar.js
- test/browser.predicates.test.js
The ability to black list hostnames was [added recently](https://github.com/rollbar/rollbar.js/pull/319) but doesn't appear to actually be used.
I'm not overly familiar with the Rollbar source, but from what I can see it simply needs to be added to the list of predicates (in the inverse form, so it returned true if not blacklisted).
> Ensure hostBlackList is considered when filtering errors

- src/browser/telemetry.js
Fixes #413 
There is something like a memory leak, at least it has the same effect if it is not classically a leak. We were storing wrapped properties for every network request rather than just the wrapped properties on the XHR prototype. While this is maybe technically correct in some abstract sense as it allows us to properly unwrap everything if the configuration changes, we don't really need to unwrap those for things to still work. Also storing them will result in a growing memory footprint without any real cleanup mechanism. The alternative to this fix is to have the onreadystatechange handler do some cleanup when the request is done, but this is fix is adequate.
> we should not be storing the props for every request, only the prototype one

- .npmignore
2.2.7 breaks our jenkins build because we do a git clean on our own git dir during checkout which fails because rollbar has dropped a `vendor/JSON-js/.git` file into `node_modules/rollbar`.
I don't have a whole lot of experience with git submodules, so I opted with the simple solution of excluding the .git file from the npm package.
> don't package .git file in npm

- index.d.ts
Fixes the invalid type definition of the newly added `lambdaHandler`
> Fix missing argument name in TypeScript definition file

- src/telemetry.js
- test/telemetry.test.js
Let me know if this is just a case of me doing it wrong, but here are the repro steps to what I was seeing:
1.) Initially configure Rollbar with `maxTelemetryEvents: 15` or something that isn't `100`.
2.) At some point in the future, call `Rollbar.configure`, e.g.
```javascript
Rollbar.configure({
payload: {
person: { id: 1, email: 'me@example.com' }
}
});
```
__Expected__: `maxTelemetryEvents` is still set to 15.
__Actual__: `maxTelemetryEvents` is reset to the default (100).
> Fix: calling Rollbar.configure shouldn't clear telemetry config.

- src/server/logger.js
As discussed in issue [#470](https://github.com/rollbar/rollbar.js/issues/470) this PR tries to keep verbose logging without the debug module
> Migrate from debug to binding console

- src/browser/telemetry.js
Correctly update the telemetry scrubbing settings in the browser instrumentation configure method
> Fix how telemetry is reconfigured

- src/browser/errorParser.js
I'm getting errMsg.match is not a function error from https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.3.1/rollbar.min.js
> fixes errMsg.match is not a function error

- src/browser/globalSetup.js
Accessing properties of an event as part of an event handler on the window can violate the browser's SOP, so be careful
Fixes #488
> Be defensive when accessing event properties

- src/browser/transforms.js
- src/react-native/transforms.js
- src/server/transforms.js
- src/utility.js
- test/utility.test.js
Fixes #508 
Fixes #509 
We should not modify an object in-place to scrub it.
We should not use an unanchored regular expression for testing whether to scrub a key.
> Proper scrubbing

- index.d.ts
I found while writing a Typescript project that it's a type error to specify the environment while creating a rollbar object. This adds that specific option.
Are there any other options that are missing from this type? Just looking at [`Rollbar.defaultOptions`](https://github.com/rollbar/rollbar.js/blob/05a043a26ab5184c0a7b9aeaedf92845c23db025/src/server/rollbar.js#L506), it looks like these are missing:
- `host`
- `framework`
- `showReportedMessageTraces`
- `notifier`
- `scrubHeaders`
- `addRequestData`
There might be others, I haven't scrubbed the whole codebase for usages of this object.
> Add environment to options type

- src/rollbar.js
Curently we send an item to rollbar with an array of telemetry events leading up to this specific
item, but that queue does not contain any information about the item it is embedded inside. This was done so that we would not duplicate data being transmitted. The relevant event could just be tacked on to the end of the list by the backend.
This leads to some oddities in the UI based on the way we source information about the related item
to embed in the telemetry data. Rather than further complicate that process, we can simply include
the information about the current item in the telemetry queue and not have to do that extra work on
the backend. The amount of extra data being transmitted is relatively inconsequential.
> Include current item in telemetry queue

- src/react-native/transforms.js
Two small fixes for React Native support:
- Removed `require('url')` as it's not used at all and is not available in React Native environment at all (another workaround is to `npm i url`), as opposed to nodejs.
- Fixed typo for `RegExp` as JS is case sensitive and this was throwing an `undefined` error.
> Fixed tiny React Native issues

- README.md
- src/telemetry.js
- test/telemetry.test.js
Adds the capability to filter out any telemetry event with custom filter function.
Resolves #519.
> Add filterTelemetry callback configuration parameter

- src/react-native/predicates.js
- src/react-native/transport.js
better diagnositics for understanding when predicates stop reporting, and replace error with catch as the fetch promise api is slightly different
> Some minor fixes for react native

- README.md
Hey guys!
According to Angular's documentation, service locator pattern should be avoided unless there are no other options. In this case there are other options, we can inject `Rollbar` using `@Inject` decorator.
In former version, if you are not using `RollbarService` in different places of your application, `Rollbar` will be initialized only when error has happend. That's causing lack of telemetry information. `Rollbar` should be initialized on application initialization to collect all telemetry data.
To achieve that, we can inject it into root component of application or we can inject it into `ErrorHandler`, which is a part of Angular's core library and is initialized at the very beginning.
Would be awesome if you consider merging this change. It might help other Angular and Rollbar …
> Update Angular integration guidelines

- src/rateLimiter.js
- test/browser.predicates.test.js
If it is the per minute one or the global one before we said it was the global one, this change discriminates between the two
Fixes #517
> change the rate limiter to accurately say which limit was hit

- README.md
The current AWS Lambda docs are confusing as to whether one needs to set callbackWaitsForEmptyEventLoop to false or not. Add some explanation of the fact that you do not need to set it to false, it is not recommend to set it to false anyway, but that things will work regardless of what it is set to.
> Explain callbackWaitsForEmptyEventLoop

- src/browser/bundles/rollbar.js
- src/browser/bundles/rollbar.noconflict.js
- src/browser/rollbar.js
- src/browser/shim.js
Fixes #549 
I was stupid, you can't check for existence of a name as truthy check if the name is possibly undefined. You need to use `typeof name !== 'undefined'`. This does that for the uses of window. The code was written to fall back if window is unavailable, but the top level check for window was broken.
> Proper global checks

- README.md
- index.d.ts
- src/browser/rollbar.js
- src/browser/telemetry.js
- src/react-native/rollbar.js
- src/server/rollbar.js
- src/telemetry.js
Introduce the `includeItemsInTelemetry` option to allow turning on/off the automatic inclusion of previous items sent to Rollbar. We make this default to false on the server side and true everywhere else.
> More telemetry options

- src/browser/rollbar.js
- src/notifier.js
- src/react-native/rollbar.js
- src/server/rollbar.js
- test/browser.rollbar.test.js
Fixes #582
We use the `node-extend` package for merging objects. This treats arrays
as objects with integer keys when it attempts to deep merge objects.
This is problematic for configuration options which are arrays because
what happens is that setting a configuration option to an array value
will just overwrite part of the array (depending on the sizes of the
arrays involved).
We do not actually require deep merging for the places that we were
using it, so instead I switch to using shallow merging for configuration
data, this allows arrays (like scrubFields) to become overwriteable.
> Options should override not merge

- index.d.ts
`scrubHeaders` is missing from the type definition.
> Add scrubHeaders as optional configuration

- package.json
- src/api.js
- src/browser/rollbar.js
- src/browser/telemetry.js
- src/browser/transforms.js
- src/merge.js
- src/notifier.js
- src/queue.js
- src/react-native/rollbar.js
- src/rollbar.js
- src/server/rollbar.js
- src/telemetry.js
- src/transforms.js
- src/utility.js
- test/notifier.test.js
- test/server.transforms.test.js
- test/utility.test.js
Create a custom version of object merging which does exactly what we want rather than working around extend.
extend merged arrays as if they were objects with integer keys, i.e.
`extend({a: [1, 2, 3]}, {a: [42, 9]}) -> {a: [42, 9, 3]}`
If you don't want that behaviour then you also have to give up deep merging.
This PR implements a function `merge` which:
1. treats array values as primitives and does not recurse within them
2. deep merges objects
3. always returns an object which is independent of any of the arguments
This means to get your own copy of an object you can call `merge(yourObject)` rather than the usual `extend({}, yourObject)`. This gets rid of the extra `{}` first argument in almost all calls to extend. This implementation might not be exactly what one might want for …
> Replace extend with our own implementation

- src/utility.js
This should never happen, I still don't understand how it is possible to get this function called with a non-string, but apparently it has happened. Such is Javascript. So we should not throw, instead have a default unknown value.
> Do not throw on bad input to parseUri

- karma.conf.js
- src/browser/shim.js
Prototype redefines bind in a broken way for the purposes of partial function application. Luckily they provide `curry` which does the right thing for this use case. So if `curry` exists on Function.prototype we can use that instead of `bind` otherwise just use `bind`.
Fixes #344
> Use curry provided by Prototype if it exists

- src/utility.js
- test/utility.test.js
Fixes #592 
Calling `someArray.join(' ')` where `someArray` contains a `Symbol` throws an error. We instead call `toString()` on the symbol before putting it in the array.
> Handle Symbols in formatArgsAsString

- src/server/rollbar.js
> Do not return result of inner handler for lambda

- index.d.ts
added CaptureIp type (boolean plus string "anonymize") and allow code_version top level config key to avoid typescript compiler errors.
The changes are hand-crafted - I hope I got everything right.
Please note that you might need to add a type hint in your config object literal:
```
{
captureIp: <CaptureIp>'anonymize'
}
```
instead of
```
{
captureIp: 'anonymize'
}
```
> updated typescript type declarations from 2.3.3 to 2.4.2

- src/browser/shim.js
Don't use curry or bind, it is unnecessary and curry is still not the
same as `.bind(null, ...)` even though it makes it seem like it is. We
can just create a new constructor that does what we want.
> Fix for Prototypejs

- src/rateLimiter.js
Related to #648 
I am not sure what is causing that particular issue, but looking at the rate limiter there are a couple scenarios that could result in odd behaviour, one being clock skew so this attempts to be a little more resilient to potential clock issues.
> Make the rate limiter a little more resilient

- src/browser/rollbar.js
Fixes #642 
When we get an unhandled promise rejection, we were calling `String(reason)` on the string if it did not have a message property, that is bad. We instead should attempt to stringify the object.
> Stringify rejected promise reason

- src/rollbar.js
People Tracking does not work on the rollbar-react-native project. As talked about in [this](https://github.com/rollbar/rollbar-react-native/issues/39) closed issue. I have tracked down the issue to this JS library, where the configure method does not merge in the configured payload data into the notifier and telemeter.
> fix(setPerson): configure notifier and telemeter with payload params

- src/utility.js
In scrubber, changed cloning to partial cloning (similar to immutable/persistent data structure), to avoid changing how unscrubbed data are stringified when send to server. See #670.
> use partial cloning in scrubber

- src/browser/telemetry.js
- src/telemetry.js
- test/telemetry.test.js
Fixes #678 
Maybe does something for #667 
1. We do our monkey patch of the onreadystatechage handler inside send which implies that we will never actually see readyState == 1 because of the semantics of readyState. This change makes it so we actually start tracking network requests sooner which means that an error while the request is in-flight will contain telemetry data about the request. The previous behaviour was that we only saw the request in the telemetry data if the request completed before the error.
2. Run the telemetry filter at capture time to handle the majority of cases, but re-run on the way out of copy to handle network telemetry event race conditions
> Telemetry rework

- src/browser/errorParser.js
> Use the constructor name on the error if there is one

- src/browser/rollbar.js
In #549, support was added for using `self` in web workers, instead of `window`. This was called `gWindow`. However, `addTransformsToNotifier` continued to use `window`. 
Before this, if I called `Rollbar.init` inside a web worker, it would throw an exception. Now it does not.
I tried to rebuild using `npm run-script build` and I got an unrelated-seeming error:
```
ERROR in ./src/utility.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../vendor/JSON-js/json3.js in /Users/paulbiggar/projects/rollbar.js/src
@ ./src/utility.js 22:26-63
Warning: Task "webpack:2" failed. Use --force to continue.
```
Also, the generated files had lots of unrelated changes, so I didn't include them. Presumably there's some process that updates them.
> Support web workers by passing gWindow instead of window

- src/browser/rollbar.js
- src/react-native/rollbar.js
- src/rollbar.js
- src/server/rollbar.js
- src/telemetry.js
- src/utility.js
- test/browser.rollbar.test.js
- test/telemetry.test.js
Fixes https://github.com/rollbar/rollbar.js/issues/659
Allows `captureEvent()` to be used as before with default event type `'manual'` or to specify an event type, by allowing flexible argument order similar to the way `log()` works.
Example:
```
captureEvent({foo: 'bar}, 'info'); // defaults to 'manual' event type
captureEvent('log', {message: 'bar}, 'info'); // Flexible argument ordering allows event type to be first argument
```
> Allow telemetry captureEvent to specify optional event type

- index.d.ts
`@types/aws-lambda` allows the event to be typed as shown here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/index.d.ts#L1028
Wrapping the handler with `lambdaHandler()` removed the `@types/aws-lambda` typing. Forcing the `event` to always be of type `object` breaks the expected type of `event` in the handler. This change would enable you to type `lambdaHandler()` similarly to `Handler` from `@types/aws-lambda`. It would reinstate the desired type of `event` for the handler.
It should also be considered to enable typing of the result and to use the `Context` type from `@types/aws-lambda` instead of `object`.
> Improved LambdaHandler event typing

- Gruntfile.js
- Makefile
- examples/universal-browser/test.html
- karma.conf.js
- package-lock.json
- package.json
- test/examples/universalBrowser.test.js
- test/notifier.test.js
I looked at a few different ways of doing this. WebDriver/Selenium and other e2e frameworks for example. 
My criteria was:
* Able to load the HTML as in a browser, loading all assets, etc.
* Able to load rollbar.js in any of the ways available and/or recommended.
* Able to work with all of the front end frameworks.
* Able to verify successful and working rollbar.js load and ability to send an event.
In the end, Karma was able to do everything needed, and was already 90% configured for what we need here. 
Initially I expected each example app might need its own Karma config, and therefore separate entries in the Travis matrix. However, the changes to the root config aren't that bad and so far I expect everything will work under one config just fine.
> Enable tests for examples, and add first test

- src/utility.js
Fixes: https://github.com/rollbar/rollbar.js/issues/712
In some cases, Firefox throws with `Exception` type rather than `Error`. The object conforms to the same expectations, and we can successfully build the backtrace from it. This change recognizes the Exception type as a kind of Error.
> Handle Firefox Exception type like Error

- src/browser/transport.js
Cordova support is driving the need for this, but it can be used by anyone who makes a `RollbarProxy` object available.
> Enable RollbarProxy for sending Rollbar events

- src/react-native/transport.js
Fixes https://github.com/rollbar/rollbar.js/issues/723
Add the missing transport for sendJsonPayload.
Current rollbar.js lacks test automation for the react-native interface. Newly written test automation was used to test this update, but it is not ready to push and merge. Several dependencies need to be resolved in order for it to work in travis.
> Enable sendJsonPayload for react-native

- src/server/rollbar.js
- src/server/transport.js
- test/server.transport.test.js
Uses response headers from the Rollbar API to avoid transmitting while rate limiting is in effect.
If an API response returns statusCode: 429, and 'x-rate-limit-remaining': 0, API requests will be dropped until x-rate-limit-remaining-seconds have elapsed.
Because the user may change rate limit settings in the Rollbar dashboard, it has been requested to poll every 60 seconds to see if the rate limit status has changed. This implementation sets its remaining seconds to a maximum of 60. This accomplishes the same end as continuous polling, but only attempts to send when there is an actual event to transmit.
> Enable rate limiting for node/server

- examples/error.html
- src/browser/rollbar.js
- src/server/rollbar.js
- test/browser.rollbar.test.js
- test/server.rollbar.test.js
Fixes https://github.com/rollbar/rollbar.js/issues/726
Previously, updating `captureUncught` or `captureUnhandledRejections` in `Rollbar.configure` would have no effect. This PR allows both enabling and disabling via `configure` in both the browser and server/node environments.
This PR also adds browser and server tests for unhandled error and rejection behavior, as well as tests for enabling/disabling via the constructor and configure.
> Allow enable/disable uncaught errors/rejections in .configure

- src/server/rollbar.js
AWS Lambda allows this timer to run and execute its function after the Lambda function has exited successfully. This results in spurious and unexpected "Function timed out" errors in the Rollbar dashboard. Clearing the timer on exit solves the issue.
> Clear timer to avoid unexpected "Function timed out" errors

- webpack.config.js
Fixes: https://github.com/rollbar/rollbar.js/issues/732
Workaround for webpack issue described here:
https://github.com/webpack/webpack/issues/6677
https://github.com/webpack/webpack/issues/6642
With a proposed fix here, but no ETA: https://github.com/webpack/webpack/issues/6525
There are various suggestions on how to set `globalObject`. This PR produces the same UMD code as before the update to webpack 4.
> Workaround webpack/webpack issue #6642, #6677

- src/browser/rollbar.js
- src/queue.js
- src/react-native/rollbar.js
- src/server/rollbar.js
- test/queue.test.js
To support SDK dev options, adds the `transmit` option, default `true`. Set to false to fully process events, but not send to Rollbar.
> Add transmit option flag

- src/browser/globalSetup.js
- src/browser/rollbar.js
- test/browser.rollbar.test.js
On Chrome, when onerror has a null error object, uses `Error.prepareStackTrace` to send more complete error information. This allows Chrome to show the same level of detail as Firefox for these errors.
Feature is enabled by default. Set `config.inspectAnonymousErrors = false` to disable.
> Enhanced error report for anonymous errors

- src/browser/rollbar.js
- src/react-native/rollbar.js
- src/server/rollbar.js
- src/transforms.js
- test/browser.rollbar.test.js
- test/react-native.rollbar.test.js
- test/server.rollbar.test.js
- test/transforms.test.js
For internal support team diagnosis, stores the user configured options in the payload notifier object.
> Add configured options to payload notifier object

- src/browser/rollbar.js
- src/transforms.js
- test/browser.rollbar.test.js
Adds a diagnostic key to the payload, so during any troubleshooting we can see how the error was generated.
> Add diagnostic key for anonymous errors

- src/browser/detection.js
Web workers don't have document at all, so this was failing with "document is not defined".
> Fix browser detection inside web workers

- src/browser/rollbar.js
- src/react-native/rollbar.js
- src/rollbar.js
- src/server/rollbar.js
- test/browser.rollbar.test.js
Rollbar.js discards consecutive identical uncaught errors after sending the first error. This new flag allows overriding that behavior and transmitting all duplicate errors.
> Add ignoreDuplicateErrors config flag

- src/browser/transforms.js
- src/react-native/transforms.js
- src/server/transforms.js
- test/browser.rollbar.test.js
- test/browser.transforms.test.js
- test/server.rollbar.test.js
Adds a more meaningful message when a Rollbar message is blank. This typically occurs when an argument is intended to be non-null, but is actually null or missing.
The most odd case is when calling something like `Rollbar.error(null)` in browser js. The message that shows up in the dashboard is:
`{"extraArgs":[null]}`
These cases will now use the message 'Item sent with null or missing arguments.', which should be more helpful to both the user and Rollbar customer support.
> Use better message when rollbar.log is called with null or missing arguments

- src/browser/rollbar.js
- test/browser.rollbar.test.js
Improved handling of direct calls to `onerror` on Chrome. 
Fixes the verification example:
`window.onerror("TestRollbarError: testing window.onerror", window.location.href)`
And generally permits directly calling `onerror` without a full arguments list.
> Improve detection of chrome anonymous errors vs omitting the error arg

- examples/error.html
- src/browser/errorParser.js
- src/browser/rollbar.js
- src/browser/transforms.js
- test/browser.rollbar.test.js
- test/browser.transforms.test.js
1. Enables nested errors, and `trace_chain` payloads in the browser environment.
2. Converts DOMException to a trace chain event by creating an error object for the DOMException's error name.
> Send DOMException as trace_chain; allow nested errors in browser SDK

- src/transforms.js
- test/browser.rollbar.test.js
1. When `item.err` is present, store the raw error in the `notifier.diagnostic` key.
2. Fix the key name format for `is_anonymous` to be snake case like the rest of the API request payload.
> Add raw error diagnostic; fix key format for API payload

- src/browser/rollbar.js
- src/browser/shim.js
Several requests for this. These wrappers cause problems in no-conflict scenarios.
> Allow disable of global event wrappers

- package.json
Added `ccmonth`, `ccyear`, `ccname` as a scrubField.
According to [Google Developers](https://developers.google.com/web/fundamentals/design-and-ux/input/forms/#recommended_input_name_and_autocomplete_attribute_values), in the credit card form the name attribute values `ccmonth` `ccyear` `ccname` are recommended because of autocomplete. This PR allows users to use autocomplete & rollbar.js  without setting `scrubField`.
> Add ccmonth, ccyear, and ccname as a scrubFields

- package.json
Added `cvc` as a scrub field.
As [google document](https://developers.google.com/web/fundamentals/design-and-ux/input/forms/#recommended_input_name_and_autocomplete_attribute_values) says, "cvc" could be used as a name attribute to create credit card number form. To do this, we can allow users to use auto-completion when they fill the form. Therefore, I think it's reasonable to add "cvc" to scrub list.
> Add cvc as a scrub field

- karma.conf.js
- package-lock.json
- src/server/rollbar.js
- src/server/transforms.js
- src/utility.js
- test/server.transforms.test.js
If `request.body` in the payload is JSON, parse and scrub it. Node/server env only.
The intent is to ensure sensitive data in the request body isn't leaked. Therefore, if there is any error parsing the JSON, the body will be set to null and a diagnostic error will be added.
The new config option `scrubRequestBody` is true by default. Set false to skip parsing and scrubbing.
Also in this PR:
> Scrub request body

- src/browser/rollbar.js
Fixes: https://github.com/rollbar/rollbar.js/issues/765
Changes the default behavior to _not_ wrap global event handlers. The wrappers result in wrong and confusing source locations in Chrome. When the feature was first implemented, it was intended to provide better source locations on older browsers. At this point the number of Chrome installs far outweighs the number of IE10/11 era browsers.
> Change default for wrapGlobalEventHandlers

- src/browser/globalSetup.js
- src/browser/rollbar.js
Interesting edge case where another `onerror` handler throws and catches a dummy error to generate a stack. This interferes with `prepareStackTrace`, so the fix delays waking `prepareStackTrace` until chained `onerror` handlers have run.
> Prevent prepareStackTrace from picking up stray errors

- src/browser/rollbar.js
Touching `error.stack` ensures Chrome preserves the original stack. It looks like Chrome lazy synthesizes the stack, but will not do so after prepareStackTrace returns.
> Ensure stack is preserved on chrome

- src/browser/rollbar.js
In Chrome 76, the return value of `prepareStackTrace` is used and needs to be the full stack string.
> Chrome 76 uses return value of prepareStackTrace

- src/browser/telemetry.js
- src/notifier.js
- src/transforms.js
- src/utility.js
- test/browser.rollbar.test.js
Fixes: https://github.com/rollbar/rollbar.js/issues/751
In some environments, the console methods (e.g. `log`, `debug`, etc.) have been replaced with read-only properties. No known browsers do this by default, but it appears that other code running in the browser replaces or modifies `window.console` to use read-only properties. (See examples here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Getter_only)
In strict mode code environments, Rollbar will then fail with `TypeError: setting getter-only property "debug"`. In non strict mode environments, Rollbar will silently fail to update the console methods. 
This fix sets strict mode while updating the console methods. This ensures a consistent and predictable behavior across different code environments, and …
> Recover from read-only window.console object

- src/browser/transforms.js
- test/browser.transforms.test.js
Fixes: https://app.clubhouse.io/rollbar/story/54135/rollbar-js-exception-class
Previously, when `error.name` and `error.constructor.name` are both missing, `error.message` would be used to guess the class, using a regex to look for and extract the part before the colon.
This has unintended results most of the time. In cases where the `name` property is missing, it is unlikely the class will be in the message string. Meanwhile, it's possible for other strings to match the regex and generate unexpected values that get assigned to be the error class. Besides being confusing and not useful, this interferes with grouping.
This PR makes the default behavior to assign "(unknown)" as the error class. This is the value already being used when no value can be guessed.
When `config.guessErrorClass` …
> Optionally guess error class when missing

- package.json
- src/browser/telemetry.js
- test/browser.rollbar.test.js
Fills in some gaps in network telemetry capture, and adds scrubbing for request/response JSON bodies and headers.
Enable telemetry capture for:
* Fetch request headers
* Fetch response headers
* Fetch response body
* XHR request headers
Enable scrubbing:
* Detect fetch request/response content type
* Detect XHR request/response content type
* Scrub request/response headers (XHR and fetch)
* Scrub request/response JSON bodies (XHR and fetch)
Some parts of the Fetch API are missing on IE. All features were tested for IE compat and graceful degradation.
> Network telemetry improvements

- package.json
- src/react-native/rollbar.js
- src/server/rollbar.js
- src/server/transforms.js
Stores the original error before parsing, for diagnostic purposes. This is already enabled for browser. Here, just adding to server and react native.
> Store original error in server and react native targets

- karma.conf.js
- package-lock.json
- package.json
- webpack.config.js
Fixes: https://github.com/rollbar/rollbar.js/issues/797
This PR restores the strict-loader that was removed in the migration to Webpack 4 between versions 2.6.x and 2.7.0.
Dist files built with the new webpack config have been included here to facilitate inspection and test. They will be removed before merge.
> Webpack strict mode

- .eslintrc
- package-lock.json
- package.json
- src/server/rollbar.js
Fixes: https://github.com/rollbar/rollbar.js/issues/801
Vows was previously versioned at 0.7.0, which has a call to `util.print` that results in a "not a function" error... but only sometimes. The util package in my node_modules doesn't export a `print()` function, yet everything works in my environment, and has worked in CI (which should be a clean npm environment.) Despite this seeming to work for the lucky, it is clearly wrong by code review. (I can't find an old enough version of util that it still has `print()` anywhere.)
Later versions of vows no longer use `util.print`, so this PR updates to vows 0.8.3, which looks like the last stable version.
> Update vows package to fix util dependency

- .eslintignore
- Gruntfile.js
- browserstack.browsers.js
- karma.conf.js
- package.json
Fixes: https://github.com/rollbar/rollbar.js/issues/801
Updates "npm run lint" to match current Codacy coverage, and to run without errors.
> Fix npm run lint

- src/truncation.js
- src/utility.js
- test/truncation.test.js
When calculating payload length for truncation, `payload.length` was being used. This returns the character count (or more accurately the UTF-16 code point count), rather than the UTF-8 byte count. This leads to non-ascii payloads being insufficiently truncated and then rejected by the API.
This PR uses a minimal implementation for counting UTF-8 bytes that never undercounts bytes, and rarely overcounts*. This is safe and valid to be used for truncation, and is significantly smaller and faster than a complete UTF-8 encoder. 
* It will overcount when it encounters UTF-16 surrogates (two code point chars.) These should be rare in practice, but specific support for these could be added if/when desired.
> Use correct byte size for truncation

- package-lock.json
- package.json
- webpack.config.js
Fixes security alert for serialize-javascript.
serialize-javascript could not update to a safe version while uglifyjs-webpack-plugin was still being used, so removed that dependency and updated webpack conf to use the newer terser-webpack-plugin.
> Update deprecated uglifier and ensure serialize-javascript >= 2.1.1

- src/browser/telemetry.js
- src/browser/transforms.js
- src/errorParser.js
- src/utility.js
- test/browser.rollbar.test.js
When telemetry is enabled, this optionally allows Rollbar errors to be sent for XHR or fetch HTTP status codes. Disabled by default, the new flags are:
```
autoInstrument: {
networkErrorOnHttp5xx: false,
networkErrorOnHttp4xx: false,
networkErrorOnHttp0: false
}
```
This PR also enables setting `skipFrames` when calling `Rollbar.error()`. The HTTP status error occurrences use this to allow the stack to point to where the `xhr.send()` or `fetch()` was called in the client code.
> Allow rollbar errors on xhr/fetch http status (4xx/5xx/0)

- src/server/parser.js
- test/server.parser.test.js
The matcher/parser for trace frames can handle the common form 
`'  at MethodClass.method (app/server.ts:52:4)\n'`
but not the less common example where the method name contains parens:
`'  at MethodClass.method.(anonymous) (app/server.js:62:14)\n'`
This PR updates the regex to handle both cases, and adds tests to verify a variety of common examples. The examples are based on real data, but aren't comprehensive. More examples can be added as needed.
> Allow matching method names with parens

- package.json
From my rollbar dashboard, I get code push url like:
```
http://reactnativehost//var/mobile/Containers/Data/Application/52713282-5486-4447-8D8F-683E8835FE7A/Library/Application Support/CodePush/220c9e918e33429e06837cbddcbcc0e8c0c6e5fd9519abe662c9d8d9d2eb9db5/CodePush/main.jsbundle
```
So I add an extra rule to match above url
Refer to
https://github.com/rollbar/rollbar.js/pull/780
https://github.com/rollbar/rollbar-react-native/issues/75
> Add CodePush Rewrite Rule

- .github/workflows/workflow.yml
Allows testing without publish, and allows URL verification before publish.
> Trigger s3 workflow on release created

- defaults.js
- package.json
Starting in the next release, cdn files will be served from cdn.rollbar.com.
> Use new url format for cdn

- .github/workflows/workflow.yml
s3-sync-action passes through any additional command line params to s3 sync. Add one for cache-control.
> Add cache-control

- test/predicates.test.js
Verifies the double escape behavior when passing literals in the config option.
Update: Go ahead and add a few more regex tests while I have this open.
> Test ignoredMessages with regex including escaped literal

- src/server/parser.js
Running rollbar on aws lambda with node version 12.16.1 gave me the following error:
```
Class constructor LRUCache cannot be invoked without 'new'
```
This pull request fixes it
> Fix error while initializing LRU cache

- index.d.ts
Fixes: https://github.com/rollbar/rollbar.js/issues/837
Uses the definition from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/handler.d.ts as suggested in the linked issue.
> Fix type definition to work with async handler functions

- src/predicates.js
- src/transforms.js
- src/utility.js
- test/browser.rollbar.test.js
Add a few things to the `notifier.diagnostic` key in the payload.
* is_uncaught
* Callback functions from config, if present (`transform`, `onSendCallback`, `checkIgnore`)
* Caller's type signature for `Rollbar.log()`
Payload keys are snake_case, except option keys within `configured_options` which retain their original javascript case.
> Diagnostic improvements

- examples/angular2/src/app/rollbar.ts
- examples/error.html
- index.d.ts
- src/rollbar.js
- test/browser.rollbar.test.js
The default stack trace length in Chrome and Node is 10 frames, which often doesn't include the frames related to the cause of the error.
Chrome, Safari, Node, and some other environments allow increasing the number of stack frames by setting `Error.stackTraceLimit`.
The config option, off by default, can be set at `options.stackTraceLimit`. Changing the default would impact grouping, since stack traces for the same error may now be a different length. Therefore the current behavior is preserved as the default.
> Allow configuration of stack trace limit

- src/server/parser.js
- src/server/sourceMap/stackTrace.js
- src/server/transforms.js
- test/server.parser.test.js
- test/server.transforms.test.js
Add to `notifier.diagnostic` a key showing whether a map file was found for each source file, and if so, what its URL was.
Payload keys are snake_case.
> Add diagnostic keys for node source maps

- index.d.ts
Fixes: https://github.com/rollbar/rollbar.js/issues/853
At the moment, the `LambdaHandler` type does not correctly compile,
because:
- the `Context` type is not defined
- the `Callback` type is not a generic, but is treated as such
This change fixes these errors by:
- adding an optional `TContext` to the `LambdaHandler` generic types
- adding an optional generic typing to the `Callback` type
> Fix TypeScript compilation errors

- src/utility.js
- test/browser.rollbar.test.js
Fixes: https://github.com/rollbar/rollbar.js/issues/857
Restores `item._originalArgs` and adds some related test coverage.
> Restore item._originalArgs

- src/rollbar.js
Lightstep wanted to use more "namespaced" tag names like `rollbar.<TAG_NAME>` so this PR fixes changes to use that new convention.
> Update naming convention for Lightstep open tracing span tags

- src/browser/telemetry.js
- test/browser.rollbar.test.js
Fixes: https://github.com/mozilla/pdf.js/issues/11490
In network telemetry, when reading the fetch response body, clone the response object first and read the clone.
Using any of the read methods on the original object will lock the response body when it is a `ReadableStream` type (and may have similar issues with other allowed types.)
> Clone the fetch response before reading

- src/browser/transforms.js
- src/react-native/transforms.js
- src/server/transforms.js
- src/utility.js
- test/utility.test.js
This PR adds `config.scrubPaths`, which allows scrubbing specific key locations by specifying the full path of the key. (When using `config.scrubFields`, all matching key names in the payload will be scrubbed regardless of location.)
Example:
```
config.scrubPaths = [
'request.query_string',
'client.javascript.plugins'
]
```
This makes it possible to scrub 'request.body', whereas adding 'body' to `config.scrubFields` would scrub every `body` key in the payload.
By adding `scrubPaths` as a separate key from `scrubFields`, fields that contain dots will still work and paths that don't (root keys) will also work.
This PR does not support paths that contain arrays. That can be added later if there is sufficient interest.
> Allow scrubbing by full path in payload

- src/browser/transforms.js
- src/react-native/transforms.js
- src/server/transforms.js
- src/utility.js
- test/browser.rollbar.test.js
- test/browser.transforms.test.js
- test/server.transforms.test.js
Sometimes relevant debugging context is known at the time the error is thrown rather than at the time it is caught or reported. This PR enables detecting context data on the error object and merging it with the custom data in the Rollbar occurrence.
To use the feature:
* Set `options.addErrorContext = true`.
* Set `error.rollbarContext` with the data to be included in the custom data for the occurrence.
For trace chains, context data will be merged from any errors where it is present.
> Send error context as custom data

- package-lock.json
- package.json
Since https://github.com/rollbar/rollbar.js/pull/473/ removed the use of `debug`, it doesn't seem like this package is still needed.
> Remove debug from dependency

- src/server/transforms.js
- test/server.transforms.test.js
Previously we only relied on the top URL provided by the request but failed to check if there was a base URL. This is often caused by using nested routers in libraries like express.js.
> Fixes https://github.com/rollbar/rollbar.js/issues/865
---
```javascript
const express = require('express');
const Rollbar = require('rollbar');
const rollbar = new Rollbar({
accessToken: process.env.ROLLBAR_ACCESS_TOKEN,
captureUncaught: true,
captureUnhandledRejections: true
});
const app = express();
const topLevelRouter = express.Router({ mergeParams: true });
topLevelRouter.get('/:topLevelId', (req, res) => {
rollbar.warn('test top level route', req);
res.status(200).send({
message: 'ok',
topLevelId: req.params.topLevelId
});
});
const nestedRouter = express.Router({ mergeParams: true }); …
```
> Support nested routes in the request data and context item payloads

- index.d.ts
PR #870 adds a new option, addErrorContext, which can be added to the configuration object when initializing Rollbar. This option will be included in the `Rollbar.Configuration` type in `index.d.ts`, to ensure people who type their configuration object to be able to use this option.
Fixes: #873
> Add "addErrorContext" in config type

- src/rollbar.js
Fixes: https://github.com/rollbar/rollbar.js/issues/876
Use `var` for browser compatibility.
> Remove const declarations

- index.d.ts
From Clubhouse story (69341), PR makes `options.host` available in TypeScript. 
This is somewhat documented here. (Doc could be improved.)
https://docs.rollbar.com/docs/environments#recommended-usage
And is used here:
https://github.com/rollbar/rollbar.js/blob/master/src/server/transforms.js#L35
> Add ts definition for config.host in node/server env

- src/predicates.js
- src/transforms.js
- test/browser.rollbar.test.js
Fixes: https://github.com/rollbar/rollbar.js/issues/881
Don't delete `item._isUncaught` until checkIgnore predicate.
Also adds test that runs all transforms and predicates (Other checkIgnore tests only run predicates), and resets the `captureUncaught` state between tests.
> Ensure checkIgnore receives isUncaught

- src/react-native/rollbar.js
- src/server/rollbar.js
- src/utility.js
- test/utility.test.js
Fixes: https://github.com/rollbar/rollbar.js/issues/887
> Fixes: https://github.com/rollbar/rollbar.js/issues/887 , ch72254
> Allow non-native JSON functions when not using the polyfill

- src/rollbar.js
Add explicit call to `setTag('error', true)` tag in span.
Request from LightStep
> Add call to set error tag to true

- src/rollbar.js
Add a few extra tags to the tracer's span, providing direct links to the item and individual occurrence, using the URLs described [here](https://docs.rollbar.com/docs/uuids#using-a-uuid) to ease linkages between tracing views and rollbar.
Note: I didn't see any tests related to checking the tracer span itself since that's presumably up to the implementation of whatever tracer it is, so there were none to add/update, but if any extra tests seem necessary I can add them.
> Description here
N/A
> Add item and occurrence URL as tags to tracer

- src/rollbar.js
- src/server/transforms.js
- test/browser.rollbar.test.js
- test/server.transforms.test.js
This PR fixes two issues:
* Ensures the client callback is called fro errors caught in `Roolbar.client.log()`.
* When traversing nested errors, handles `null` value of `err.nested` rather than only `undefined`.
Fixes ch74675
Fixes https://github.com/rollbar/rollbar.js/issues/898
> Improve error callback handling

- examples/csp-errors.html
- karma.conf.js
- src/browser/telemetry.js
- test/browser.rollbar.test.js
Browsers use Content Security Policy directives (provided in the HTTP response header, or in a meta tag) to govern what resources can and can't be loaded. When an attempt to load a resource is blocked, an error is written to the dev console, but no exception is thrown. Instead, the browser sends a `contentsecuritypolicy` event.
This PR listens for these events and records the error as a telemetry event, and if `errorOnContentSecurityPolicy` is set, sends a Rollbar error occurrence.
To enable/disable the feature, use these `autoInstrument` flags:
```
config.autoInstrument = {
contentSecurityPolicy: true, // enables telemetry tracking, enabled by default
errorOnContentSecurityPolicy: true // send a Rollbar error message, disabled by default
}
```
Fixes: ch72648
> Enable reporting for CSP errors

- src/server/rollbar.js
- test/server.lambda.test.js
The `Rollbar.wait()` method blocks until all Rollbar API requests have completed. Calling it before process exit ensures the last messages are sent, including uncaught exceptions that may occur before process exit.
The AWS Lambda handler has `wait()` built in for each possible exit path except the success (`resolve`) path in the async handler. This PR adds `wait()` to this code path.
This PR also makes the handler a named function for better testing and debugging, not just here but when used in Lambda projects.
This PR also adds tests for the async Lambda handler, as these tests didn't exist before. The tests cover basic usage and the specific `wait()` related scenarios for log messages on successful exit, as well as uncaught exceptions on a failing (`reject`) exit.
Fixes ch68951
> Wait in async lambda handler

- src/browser/core.js
- src/predicates.js
- src/react-native/rollbar.js
- src/server/rollbar.js
- src/utility.js
- test/browser.rollbar.test.js
- test/predicates.test.js
- test/react-native.rollbar.test.js
- test/server.rollbar.test.js
Rollbar's new standard naming convention, that applies to all SDKs, replaces usage of `whitelist` and `blacklist` with `safelist` and `blocklist`. This PR adds new config properties with updated names and deprecates the old ones.
Fixes ch69177
> Deprecate whitelist/blacklist in favor of safelist/blocklist

- index.d.ts
- src/server/locals.js
- src/server/parser.js
- src/server/rollbar.js
- test/fixtures/locals.fixtures.js
- test/server.locals.test.js
- test/server.rollbar.test.js
Enables capture of local stack variables in Node.js. To enable, set `locals: true` in the config.
This feature uses the Node Inspector API to access debugger data at runtime. The Inspector API is a wrapper for the V8 Inspector interface. While the V8 interface relies on `send()` and `receive()` functions that can't be accessed from Node, the Node Inspector API provides access to these via the `post()` method on the Inspector Session instance. Using `session.post()`, all of the DevTools protocol can be accessed, including the `Debugger` and `Runtime` interfaces, which are used here.
The initial version of this feature supports both caught and uncaught exceptions and promise rejections. Nested exceptions and trace chains are supported.
The DevTools protocol allows retrieving nested …
> Enable node.js stack locals capture

- src/server/locals.js
- src/server/parser.js
- src/server/rollbar.js
- test/fixtures/locals.fixtures.js
- test/server.locals.test.js
Follow up PR to https://github.com/rollbar/rollbar.js/pull/902 adds traversal of objects and arrays. Capture is performed to the specified depth. Options are also provided to limit the maximum number of object properties and array members captured. 
Locals capture may be enabled by setting `options.locals = true` to enable with default options, or with an object containing overrides:
```javascript
options.locals = {
depth: 2,
maxProperties: 15,
maxArray: 10
}
```
`depth` sets the depth to which objects and arrays are expanded. The previous PR supported depth = 0, which captures the value of primitive types, and displays the type of all non-primitives. This is consistent with the example in the Rollbar API doc.
**Example output, depth = 0**
```javascript
locals: {
foo: "bar",
res: …
```
> Enable depth of traversal for node local vars

- src/scrub.js
- src/truncation.js
- src/utility/traverse.js
- test/utility.test.js
The traversal logic used for scrubbing payloads has circular traversal protection to prevent infinite traversal of objects that contain circular references. The scrubbing logic always modifies a copy of objects that are scrubbed, and doesn't mutate the original object.
When scrubbing, the bug existed where when the original object was detected two or more times (circular traversal protection), the original object was used in the final payload, not the modified copy. If scrub fields existed in these objects, the unscrubbed version would be added to the payload.
This PR updates the traversal logic to use the previously scrubbed copy of the data in these cases.
Fixes: https://github.com/rollbar/rollbar.js/issues/912
> Scrub all occurrences of objects seen twice

- index.d.ts
Updates the type definition for locals to support the options added in https://github.com/rollbar/rollbar.js/pull/914.
ch78822
> Update ts types for config.locals

- src/server/locals.js
- src/server/rollbar.js
- test/server.locals.test.js
* Loads the Locals class as a separate module, so that build environments like vercel/pkg that don't have Inspector can build successfully. (See notes below)
* Adds an `enable` flag that can be toggled dynamically at runtime.
* Adds an `uncaughtOnly` flag that can be toggled dynamically at runtime.
Using the `enable` and `uncaughtOnly` flags at runtime can allow capturing locals for specific code paths or time intervals, while avoiding perf impact at other times.
Usage example:
```js
const Rollbar = require('rollbar');
const Locals = require('rollbar/src/server/locals');
const rollbar = Rollbar.init({
accessToken: 'server-token',
captureUncaught: true,
captureUnhandledRejections: true,
locals: { module: Locals, enable: true, uncaughtOnly: true }
});
```
To support non-Node build …
> Load locals as module, with enable/disable and uncaughtOnly options

- src/browser/core.js
- src/utility.js
* Safely check for undefined `window` and `document`, so non-window global objects work correctly. With this bug fixed, `captureUncaught` can be set in a Web Worker’s Rollbar instance and errors will be reported with full stack information.
* Add an additional check when identifying Chrome "anonymous" errors, skipping uncaught errors from web workers that have null Error objects but do not get sent to `prepareStackTrace()`.
Currently there aren't tests specifically for web workers. I looked into whether this is possible with the current Karma test framework, and ran into problems stubbing interfaces in the separate worker context. For now the functionality has been tested manually.
Fixes ch80345
> Enable uncaught error capture for web workers

- src/server/locals.js
Remove inadvertent console.log().
Fixes https://github.com/rollbar/rollbar.js/issues/938
> Remove console.log

- src/predicates.js
- test/predicates.test.js
Previously when matching the `ignoredMessages` array to the item, `trace_chain` items were skipped. This PR adds matching for `trace_chain` messages. 
ch78345
> Apply ignoredMessages filter to trace_chain occurrences

- index.d.ts
Updates the Typescript definitions for local variable config. These config options are described here: https://docs.rollbar.com/docs/nodejs#enabling-local-variables-in-stack-traces
These changes have been tested manually.
ch85558
> Update ts types for locals

- index.d.ts
- src/apiUtility.js
- src/browser/transport.js
- src/queue.js
- src/utility.js
- test/apiUtility.test.js
- test/browser.transport.test.js
- test/queue.test.js
- test/utility.test.js
From https://github.com/rollbar/rollbar.js/issues/948 we decided to add `maxRetries` and `timeout` parameters to the rollbar config:
```javascript
var rollbarConfig = {
retryInterval: 10000,
maxRetries: 3, // Only used if retryInterval is set
timeout: 5000, // HTTP Requests timeout
...
};
```
https://github.com/rollbar/rollbar.js/issues/948
> Read timeout from options and pass it to the XMLHttpRequest

- src/transforms.js
- src/utility.js
- test/transforms.test.js
> This change allows a promise to be returned from the options.transform function.  The existing codebase
> currently throws away the return value of the transform function, but the new code allows async behavior
> to be executed in the transform function, invoking the callback when the async behavior has settled.
> Added ability to use async transforms

- package-lock.json
- package.json
Resolves dependabot alert by emoving unused mootools package.
Updates to latest 4.x webpack. However, the dependabot alert for set-value cannot be resolved without webpack 5.x. This would require dropping support for Node 8.x.
sc91458
> Remove unused mootools, bump webpack

- index.d.ts
Willing to add Rollbar to a project, I noticed that we are missing the declaration of `item` in the `transform` since the PR #650.
> Fix transform declaration

- src/utility.js
- test/browser.core.test.js
- test/server.rollbar.test.js
This PR guards against circular references in user data (e.g. custom data object) by cloning the data and removing the circular references.
**Why is this necessary?**
The linked issue report (https://github.com/rollbar/rollbar.js/issues/955) notes that the merge function in Rollbar.js errors on the circular references. But JSON serialization will also fail, even if it didn't fail during merge. The circular reference causes an infinite traversal and stack overflow.
**Why can't this be solved within the merge function?**
That's the first solution I considered. It would have had the advantage of adding circular reference protection everywhere merge is used. However, merge doesn't traverse arrays (except the root, if it is an array), and adding array traversal would change its existing …
> Handle circular references in custom data

- src/browser/telemetry.js
- test/browser.rollbar.test.js
Fixes #999 
When using the fetch API, if the server responds with a successful response and a content type of json, the body is parsed as JSON. However, if the body is empty, this causes a JSON parsing error.
- Fix #999
> Prevent error when fetch response has empty body

- index.d.ts
Improve typescript type definition.
Added types for Payload instead of using `object`
Added comments with links to documentation
Added comments to aid in understanding code_version
Added optional Promise return type for transform
**Motivation**:
I spent hours trying to troubleshoot and figure out why items were not being matched up with source maps and the typescript definitions left me confused and unsure about how to configure the payload property because the documentation, at times, is not explicit about where a property lives.
For example, this page https://docs.rollbar.com/docs/source-control#serverroot makes it seem like there is a root level configuration option called `server` (which as far as I can tell that is not the case)
And this example seems to show the `server` property in …
> Typescript definition improvement: Added types for payload property

- index.d.ts
The type declaration for `LocalsSettings` has a wrong key name. Fixing this won't break any existing clients, since the code that reads this object doesn't support using the wrong key name.
Fixes: https://github.com/rollbar/rollbar.js/issues/989
> Fix LocalsSettings type

- src/browser/telemetry.js
This change prevents an error being thrown by the rollbar sdk in a corner case where it thinks a response should be JSON but it is empty.
Both me and [the original author of the fix](https://github.com/rollbar/rollbar.js/pull/1001#issuecomment-1069391850) couldn't cause a test to fail. In my opinion this shouldn't prevent this change from being fixed as it is minimal.
- Fix #999
> don't fail when body is empty

- src/browser/telemetry.js
Adding the `securitypolicyviolation` listener to the window object works on some browsers, including chrome, and headless chrome used in the tests. However, it doesn't work on Safari, and the spec requires it to be added to the document object, not the window object. https://developer.mozilla.org/en-US/docs/Web/API/SecurityPolicyViolationEvent
This PR adds the listener to the document instead of the window.
Fixes https://github.com/rollbar/rollbar.js/issues/978
> Add CSP listener on document, not window

- src/browser/transforms.js
- src/errorParser.js
- src/server/transforms.js
- test/browser.transforms.test.js
- test/server.transforms.test.js
This PR adds support for the Error cause option enabled in Node 16.9, Chrome 93, and other browsers. (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error#browser_compatibility)
This PR leaves the existing `Error.nested` functionality for back compatibility with existing Rollbar.js usage and with earlier Node and browser versions. When `Error.nested` is present, it is preferred, preserving existing behavior.
Fixes https://github.com/rollbar/rollbar.js/issues/1010
> Support error cause

- package-lock.json
- package.json
- src/server/parser.js
The async package dependency needed to be updated from v1.x to 3.x to pick up a security update. There have been interface changes since then, so a small refactor was also needed to work with the current async interface.
The specific changes that affect rollbar.js happened in async v2.0.0:
> filter, reject, some, every, detect and their families like {METHOD}Series and {METHOD}Limit now expect an error as the first callback argument, rather than just a simple boolean.
https://github.com/caolan/async/blob/master/CHANGELOG.md#breaking-changes-1
This PR updates the calling convention for callbacks, and removes usage of `fs.exists` which is is both deprecated and incompatible with the current async interface.
> Refactor to use current (3.x) async package

- src/api.js
- test/browser.core.test.js
- test/browser.rollbar.test.js
- test/react-native.rollbar.test.js
There are concerns that when sending an occurrence, the write of the POST request payload can be blocked, blocking the caller. This is specifically about the request write not completing, not about any delay or timeout related to the response, which is already async.
While the http response completes async, the request is performed on the caller's thread. There are concerns that the caller could be blocked in some cases.
This PR uses a zero setTimeout to get off the caller's tick before making the request. This PR also updates all tests that relied on the request being synchronous. (Typically tests that inspect the request.)
Notes:
This PR adheres to this project's es5 syntax.
The execution is kept synchronous until the payload is fully constructed. Making these paths async would cause an …
> Perform occurrence POST write async

- src/browser/telemetry.js
- src/utility/headers.js
- test/browser.rollbar.test.js
The network telemetry code paths rely on the standard `Headers` object for case insensitive handling of request headers. While `Headers` is part of the fetch API standard, and has been included in browser implementations since fetch was first introduced, there are some fetch polyfills that don't implement `Headers`.
This PR uses a minimal polyfill when `Headers` is undefined. Though referred to here as a "polyfill", it is not added to the window object and does not replace or export any global functionality. It is only used internally by Rollbar.js.
Notes:
* This is implemented in Rollbar.js in order to not take a new dependency.
* The implementation is as minimal as possible to keep package size small.
* Users of the componentized build who do not include telemetry will see no change in …
> Polyfill the fetch Headers object if needed

- src/browser/telemetry.js
- test/browser.rollbar.test.js
When enabled via the Rollbar config, network telemetry can capture the response body for fetch requests. When this was originally enabled, it worked in browser, but was finicky depending on the version of headless chrome used in the tests. Recently, the previously working test started failing.
When the response body is a readable stream, the Rollbar handler must clone the response before reading the stream. The stream is locked once read, and cloning the stream allows safely reading it without reading the original. The code path already did this, but there's another requirement for `response.clone()`. It must be the first access to the response, or it will throw a `TypeError`.
The test started failing because headless chrome no longer accepted the readable stream used in the mock, and …
> Fix response body capture for fetch telemetry

- src/apiUtility.js
- src/browser/transport.js
- src/browser/transport/fetch.js
- src/browser/transport/xhr.js
- test/apiUtility.test.js
- test/browser.transport.test.js
This PR adds a `fetch` transport for sending Rollbar payloads. This enables compatibility with Service Workers, and with manifest v3 extensions which now use a Service Worker for the background script.
The PR introduces a new optional config option, `defaultTransport`. When set to "fetch" or "xhr", this transport will be used when available. The default when not set is "xhr". When only one transport is detected to be available, that one will be used regardless of the `defaultTransport` setting.
Since we have two transports now, these are moved into a /transport/ subdir. This causes a large block diff in the PR for the existing xhr transport code. None of that code has been changed, just moved to a new file.
- Fix [SC-118535]
https://github.com/rollbar/rollbar.js/issues/1040
> Enable compat with service workers and v3 extensions

- index.d.ts
According to [the documentation](https://docs.rollbar.com/docs/javascript#ignoring-specific-exception-messages), it is possible to give regular expressions for `ignoredMessages`. However, this option was typed as `string[]`.
- https://docs.rollbar.com/docs/javascript#ignoring-specific-exception-messages
> Update `ignoredMessages` type definition.

- index.d.ts
`person.id` in the Rollbar config should be nullable as documented.
Example:
```
payload: {
person: {
id: null
}
}
```
This PR makes the Typescript type definition nullable.
Fixes https://github.com/rollbar/rollbar.js/issues/1058
https://app.shortcut.com/rollbar/story/120519
> Typescript: make type for person.id nullable

- index.d.ts
Adds missing type definition for `retryInterval` in the Configuration object.
Fixes https://github.com/rollbar/rollbar.js/issues/1032
https://app.shortcut.com/rollbar/story/120521/
> Typescript: add retryInterval to Configuration definition

- src/browser/core.js
- src/react-native/rollbar.js
- src/server/rollbar.js
- src/transforms.js
- test/transforms.test.js
Currently the defaults from the config override the updated values from the user transform function. Instead, the transform should override the defaults.
This PR adds the default payload options in its own step, so that it is present during the user transform. 
Fixes
https://app.shortcut.com/rollbar/story/120633/ 
https://github.com/rollbar/rollbar.js/issues/1026
> Add default payload keys before the custom transform runs

- index.d.ts
In many places, the type definitions for callback functions use the `object` type for payload or item arguments. This makes the object opaque and no properties can be accessed in the callback.
This PR updates these to use a generic dictionary type. 
Fixes
https://app.shortcut.com/rollbar/story/120642/
https://github.com/rollbar/rollbar.js/issues/985
> Replace `object` type defs with dictionary type

- src/browser/transport.js
Provides the outer `this` to the closure function. This affects Angular users.
Fixes
https://github.com/rollbar/rollbar.js/issues/1080
https://app.shortcut.com/rollbar/story/120687/
> Provide `this` to closure

- .github/workflows/ci.yml
- index.d.ts
- src/browser/core.js
Enables code compatibility between Rollbar-react, Rollbar.js and Rollbar-react-native, including Typescript compatibility.
Allows the same initialization, whether the target is web/JS only or JS + Native.
```javascript
const rollbarReactNative = new Client({/* config */})
const rollbar = rollbarReactNative.rollbar
export default function App() {
return (
<Provider instance={rollbar} />
)
}
```
**How this works**
When rollbar-react-native detects it is on a web-only target, it returns a browser-js instance. When it is on a web + native target, it returns a rollbar-react-native instance with a browser-js instance at the `rollbar` property.
This PR allows the app code to access the browser-js instance at the `rollbar` property regardless of which instance type is returned.
Fixes …
> React + React Native compatibility

- src/browser/telemetry.js
- test/browser.telemetry.test.js
> Please include a summary of the change and which issues are fixed.
> Please also include relevant motivation and context.
At Fingerprint.js we have experienced several issues with our customers who use Rollbar. Some telemetry events weren't captured due to unsupported `URL` type in `fetch` / `XHR` (see Parameter section - the `URL` type is valid argument type for `fetch`).
I added support to rollbar`Instrumenter` and covered this behaviour with unit tests.
`fetch` and `XHR` support any object with [stringifier](https://developer.mozilla.org/en-US/docs/Glossary/Stringifier), so I can extend this condition to any object with `toString` method, thought it might be not really useful. Feel free to discuss the solution
I didn't create …
> feat: Support `URL` object in `fetch` / `XHR` telemetry

- examples/angular2/package-lock.json
Remove is_js library, for security reasons
- Fixes [this story](https://app.shortcut.com/rollbar/story/131887/rollbar-js-remove-usage-of-is-js-from-rollbar-js-sdk#activity-133676)
> Remove is_js library from package-lock.json

- .github/workflows/ci.yml
- test/server.locals.test.js
This PR fixes a failing test running over false assumptions around node/v8 locals in stack traces.
After careful testing, beginning Node.js 18, it seems locals are _only_ present in top frames. However, I wasn't able to pinpoint documentation about this.
> [!NOTE]
> This PR also updates CI to run installs and tests under lts nodes 14 through latest.
> Don't look for for non-top frame locals in node >=18 during locals tests

- .github/workflows/ci.yml
- .gitmodules
- .npmignore
- README.md
- vendor/JSON-js/README
- vendor/JSON-js/cycle.js
- vendor/JSON-js/json2.js
- vendor/JSON-js/json3.js
- vendor/JSON-js/json_parse.js
- vendor/JSON-js/json_parse_state.js
This PR removes the only submodule in the workspace, a forked version of JSON-js @ https://github.com/rollbar/JSON-js and integrates it directly into the project.
The last time the code in the fork was changed is 2015, and given we only seem to use `json3`, it does not seem like we're using any of the modified code.
> [!NOTE]
> This was mainly done with the aim of making the move to a monorepo easier.
> Removed JSON-js submodule and integrated the modified json3 directly

- src/server/telemetry/urlHelpers.js
- test/server.telemetry.test.js
`rollbar.js`, with autoInstrument turned on, will break all http/https requests in node v20+ that use `URL` as the first parameter to the request method.
The impact of this should be pretty large as the very popular [got package](https://www.npmjs.com/package/got) uses this fn signature under the hood for all of it's requests.
In node v20, [changes were made to the initialization of urlSearchParams](https://github.com/nodejs/node/commit/e3bb66813260440545a1fd4412f588f2ad1f18fe) causing a need to update how to sniff out what a URL is. Node made the underlying modification within their code, however rollbar.js has not updated it's `mergeOptions` function which was originally modeled off the nodejs internals that were changed.
Node internally, now appears to be using a new internal method …
> Fix server autoinstrument mergeOptions behavior in node v20+

- package-lock.json
- package.json
Remove the `decache` optional dependency.
It's not being used anywhere and includes packages that are no longer maintained. Our static analysis tool is flagging `traverse-chain` as a critical vulnerability.
> Remove decache

- examples/vuejs3/src/rollbar.js
Fix loop in vue 3
> in **Vue 3**: when rollbar is triggered by a throw error from inside a helper or the router
> (I suspect also some other odd placed) including the vm variable can generate an infinte loop
> The (proxy) data included in vm are not really needed for debug purposes
> Allso added new. tiny feature to fire on warnings from vue
- Fix #1126
- [x ] All tests related to the changed code pass in development
> Fix Vue 3 loop

- package-lock.json
- package.json
Adds the `@rrweb/record` dependency for the session replay functionality. We do this separately to prevent the package-lock files from adding noise to the subsequent PRs.
- Part of [CAT-353/rrweb-integration](https://linear.app/rollbar-inc/issue/CAT-353/rrweb-integration)
> rrweb: Add @rrweb/record dependency for session replay functionality

- src/browser/core.js
- src/utility.js
Don't record sessions in non-browser environments.
- Part of [CAT-353/rrweb-integration](https://linear.app/rollbar-inc/issue/CAT-353/rrweb-integration)
> Add isBrowser check for to prevent recording in non-browser envs

- src/browser/replay/defaults.js
- src/browser/replay/recorder.js
* Added a new `debug` configuration option in `src/browser/replay/defaults.js` to enable or disable logging of emitted events. (`logEmits` is set to `false` by default).
* Implemented a `_logEvent` method in `src/browser/replay/recorder.js` to log emitted events in a readable JSON format, handling circular references gracefully. This method is invoked when `logEmits` is enabled in the debug configuration.
- Part of [CAT-353/rrweb-integration](https://linear.app/rollbar-inc/issue/CAT-353/rrweb-integration)
> Add rrweb event logging to console for debugging

- test/fixtures/replay/index.js
- test/fixtures/replay/rrwebEvents.fixtures.js
- test/fixtures/replay/rrwebSyntheticEvents.fixtures.js
- test/fixtures/replay/types.js
This pull request introduces a comprehensive set of fixtures and shared type definitions for `rrweb` events to facilitate testing. The changes include the creation of separate modules for real and synthetic `rrweb` events, as well as shared type definitions to standardize event handling across tests.
* **Centralized Event Export**: Added a new `index.js` file to aggregate and export all `rrweb` event types and collections (`realEvents`, `syntheticEvents`, and `allEvents`) for easier access and reuse in tests.
* **Real Event Fixtures**: Introduced `rrwebEvents.fixtures.js`, which contains a representative sample of `rrweb` events extracted from real session recordings, categorized by type. This includes events like `fullSnapshot`, `mouseMove`, `mutation`, and others.
* **Synthetic Event …
> Add rrweb event fixtures for integration testing

- test/fixtures/replay/index.js
- test/fixtures/replay/rrwebEvents.fixtures.js
- test/fixtures/replay/rrwebSyntheticEvents.fixtures.js
- test/fixtures/replay/types.js
This PR refactors the `test/fixtures/replay` module to adopt ES module syntax, replacing CommonJS. It updates all relevant files to use `import` and `export` statements, ensuring consistency and modernizing the codebase.
- [CAT-353/rrweb-integration](https://linear.app/rollbar-inc/issue/CAT-353/rrweb-integration)
> Use es module syntax for replay testing fixtures

- src/browser/replay/defaults.js
- test/fixtures/replay/rrwebEvents.fixtures.js
- test/fixtures/replay/rrwebSyntheticEvents.fixtures.js
- test/fixtures/replay/types.js
_Description by Copilot._
This pull request refactors the module export structure across several files to adopt ES module syntax (`export`/`import`) instead of CommonJS (`module.exports`). The changes improve consistency, readability, and alignment with modern JavaScript standards.
* [`src/browser/replay/defaults.js`](diffhunk://#diff-9350acc39773b09c02790ea03425fd52ecbf3501255f2d65788d54339c3a5507L5-R5): Replaced `module.exports` with `export default` for the default options object.
* [`test/fixtures/replay/rrwebEvents.fixtures.js`](diffhunk://#diff-ce692015d4c535f2f40b0b3bafdfc74a32156f6e731f7ba7b52aa35b2bb38fdeL18-R18): Converted `rrwebEvents` from a CommonJS export to an ES module export using `export const`. Removed the redundant `export { rrwebEvents };` statement. …
> Use esm syntax for replay defaults and related maintenance

- src/browser/core.js
- src/react-native/rollbar.js
- src/rollbar.js
- src/server/rollbar.js
- src/tracing/span.js
- src/tracing/tracing.js
- src/utility.js
- test/browser.rollbar.test.js
- test/tracing/span.test.js
- test/tracing/tracing.test.js
* Adds a general utility for adding attributes to an occurrence.
* Adds span attributes to the occurrence for session_id, span_id, and trace_id if there is an active span at the time of the occurrence.
* Adds an event to the current span for the occurrence.
> Add trace attributes to item

- src/browser/replay/recorder.js
- src/tracing/hrtime.js
- src/tracing/span.js
- test/browser.replay.recorder.test.js
- test/tracing/span.test.js
This PR introduces a dedicated utility module, `hrtime.js` and a new way to interface with it:
```js
import hrtime from '@tracing/hrtime.js';
hrtime.fromMillis(1000);
hrtime.toMillis([0, 1000]);
hrtime.add([0, 0], [0, 1000]);
hrtime.now();
hrtime.isHrTime([0, 1000]);
```
The reason is that I've been needing to use this in multiple modules and I don't see why its access should be dependent upon an instance of `Span`.
- Renames `sum` to `add` to follow OTEL convention @ https://github.com/open-telemetry/opentelemetry-js/blob/0c21db4621fd981200cc731d676d1a87162ee0d9/packages/opentelemetry-core/src/common/time.ts#L173-L183
> Extracted hrtime utilities in tracing to its own module

- src/browser/replay/replayMap.js
- src/tracing/id.js
- src/tracing/session.js
- src/tracing/tracer.js
- src/tracing/tracing.js
- test/replay/unit/replayMap.test.js
- test/tracing/id.test.js
- test/tracing/tracing.test.js
Extracted hexId into its own module `id.js` module with a `gen` function to generate the random hexadecimal IDs.
- Not used by tracing
- There are Ids that use the same mechanism but aren't structurally bound to otel or tracing (replay ids, session ids)
- I needed to generate replay ids to unit test dump, the unit test was isolated, and I didn't have (nor wanted) a tracing instance.
- We can unit test id generation isolatedly (there were no tests for it).
> [!WARNING]
> Not super happy with the naming scheme, open to suggestions. I favor concise, that's why I went with this, but maybe it's too much.
- [CAT-355/enable-tracesession-transport-to-moxapi](https://linear.app/rollbar-inc/issue/CAT-355/enable-tracesession-transport-to-moxapi)
> Extract tracing's `hexId` to dedicated `id` module

- src/browser/core.js
- src/browser/replay/recorder.js
- src/browser/replay/replayMap.js
- test/browser.replay.recorder.test.js
- test/fixtures/replay/index.js
- test/fixtures/replay/payloads.fixtures.js
- test/replay/integration/e2e.test.js
- test/replay/integration/replayMap.test.js
- test/replay/integration/sessionRecording.test.js
- test/replay/unit/replayMap.test.js
This PR refactors `ReplayMap` and `Recorder` following the comments in https://github.com/rollbar/rollbar.js/pull/1185.
So, several changes have been made:
- Reliance in `spanExportQueue` has been eliminated as this is going to be private.
- Decoupled the exporter from the `ReplayMap`.
- `Recorder.dump` now returns the final payload instead of acting as an opaque side-effect that creates the span.
- Decoupled `tracing` from `Recorder`, `tracing` object can be passed to the `dump` function directly.
- `context` cannot be passed and its taken from the active contextManager in the tracing object passed.
Further breakdowns can be done in Recorder and ReplayMap to improve modularity, but that'll come in the future.
All tests were updated to reflect the refactoring.
- …
> Refactor recorder and replayMap transport flow

- src/tracing/exporter.js
- src/tracing/hrtime.js
- test/fixtures/replay/payloads.fixtures.js
- test/tracing/exporter.toPayload.test.js
This PR adds a `toPayload` function to `SpanExporter` to transform spans into the OTLP format.
Integration tests are missing, will work on them on the next PR.
[CAT-355/enable-tracesession-transport-to-moxapi](https://linear.app/rollbar-inc/issue/CAT-355/enable-tracesession-transport-to-moxapi)
> Session recording otel to otlp export

- test/fixtures/replay/payloads.fixtures.js
- test/replay/integration/api.spans.test.js
- test/replay/integration/e2e.test.js
- test/replay/integration/index.js
- test/replay/integration/queue.replayMap.test.js
- test/replay/integration/sessionRecording.test.js
- test/replay/unit/api.postSpans.test.js
- test/replay/unit/index.js
- test/replay/unit/queue.replayMap.test.js
- test/replay/unit/replayMap.test.js
- test/tracing/exporter.toPayload.test.js
- test/tracing/id.test.js
Integrated `SpanExporter.toPayload` to the integration tests instead of stubbing them. I'm still not entirely happy with it because of the non-deterministic nature of the mock record function I created to emulate rrweb.
I may either create a new mock record that's deterministic, or modify the current one. Then stub whatever gives non-deterministic data like time and ids. That way, we can do a proper deep equality to make sure the complete structure that comes in and goes out is as correct as it can be.
[CAT-355/enable-tracesession-transport-to-moxapi](https://linear.app/rollbar-inc/issue/CAT-355/enable-tracesession-transport-to-moxapi)
> Exporter integration tests

- src/tracing/tracing.js
- test/tracing/tracing.test.js
Fixes the options for resource attributes and scope. The scope is temporary, and will likely be updated to use `telemetry.sdk.*` attributes, while making the scope name and version available to the app.
> Update resource and (temporary) scope

- src/tracing/exporter.js
- src/tracing/tracing.js
- test/tracing/exporter.toPayload.test.js
- test/tracing/tracing.test.js
* Wrap resource attributes, so the exporter can consume them.
* Remove the `options.resource` override in the exporter.
> Fix resource attributes

- src/tracing/tracing.js
- test/fixtures/replay/payloads.fixtures.js
- test/replay/integration/e2e.test.js
- test/tracing/exporter.toPayload.test.js
This PR uses the same fallback to get the `environment` as react-native and server when setting `rollbar.environment` in for the `resource` tracing.
Not doing this was causing a 400 Bad Request to be returned when sending the payload to moxapi.
I've also added tests to check custom attributes that must be present like `rollbar.environment`, `replay.id` and `session.id`.
As per our documentation, environment should be set inside `payload` in the config:
- https://docs.rollbar.com/docs/rollbarjs-configuration-reference#notifier
- https://docs.rollbar.com/docs/browser-js#quick-start
In all instances where we attempt to get the environment, we employ this fallback:
```py
$ rg -A1 --max-columns=120 --glob '!dist' "environment ="
src/rateLimiter.js
145:  var environment =
146- …
```
> Send environment from options.payload.environment in sesh rep

- src/browser/replay/recorder.js
- test/browser.replay.recorder.test.js
Updated the `dump` method in `src/browser/replay/recorder.js` to require a minimum of 2 events for a valid recording. That is the minimum required by the rrweb player, otherwise it won't work.
All recordings need at the very least 2 events, which are typically the Meta and FullSnapshot events.
Added test cases to cover this.
[CAT-355/enable-tracesession-transport-to-moxapi](https://linear.app/rollbar-inc/issue/CAT-355/enable-tracesession-transport-to-moxapi)
> Avoid dumping recordings with less than 2 events

- src/browser/core.js
- src/browser/telemetry.js
- src/rollbar.js
- src/telemetry.js
- test/telemetry.test.js
Initial support for 'timeline events', sending telemetry events in an otel span.
The 'rollbar-telemetry' span is ended and a new one started whenever an occurrence is sent. This ensures a span is available to send when a replay is sent.
Note:
I considered adding the events in `Telemeter.prototype.capture`, but it seems there is enough differentiation in the event types that it's better to do it in the path for each event type.
> Initial timeline events (otel telemetry events)

- src/telemetry.js
- test/telemetry.test.js
Adds the network event to the telemetry span, to be used in the timeline.
Note: This PR also fixes a longstanding bug where the timestamp from the network request wrapper was not used in the telemetry event. This caused a timestamp to be used from when the event is added to the queue.
> Add network event to telemetry span

- test/api.test.js
- test/apiUtility.test.js
- test/browser.core.test.js
- test/browser.domUtility.test.js
- test/browser.predicates.test.js
- test/browser.rollbar.test.js
- test/browser.telemetry.test.js
- test/browser.transforms.test.js
- test/browser.transport.test.js
- test/browser.url.test.js
- test/examples/angular.test.js
- test/notifier.test.js
- test/predicates.test.js
- test/queue.test.js
- test/rateLimiter.test.js
- test/react-native.rollbar.test.js
- test/react-native.transforms.test.js
- test/react-native.transport.test.js
- test/telemetry.test.js
- test/transforms.test.js
- test/truncation.test.js
- test/utility.test.js
This PR migrates all test files from CommonJS to ES modules—except for Vows-related server tests—by replacing require() calls with import statements, appending .js extensions, and updating async patterns where needed.
[SDK-489/partial-test-migration-to-es-modules](https://linear.app/rollbar-inc/issue/SDK-489/partial-test-migration-to-es-modules)
> Migrate cjs to esm: utility, core, general, platform and browser tests

- test/server.lambda.mocha.test.mjs
- test/server.locals.constructor.mocha.test.mjs
- test/server.locals.error-handling.mocha.test.mjs
- test/server.locals.merge.mocha.test.mjs
- test/server.locals.test-utils.mjs
This PR migrates the server test `locals` to mocha from vows.
The `server.locals` test file was gigantic. I've broken it into multiple parts and added a small utility file with the shared stuff (just a couple dozen lines).
[SDK-490/migrate-vowsjs-to-mocha](https://linear.app/rollbar-inc/issue/SDK-490/migrate-vowsjs-to-mocha)
[SDK-491/complete-server-test-es-module-migration](https://linear.app/rollbar-inc/issue/SDK-491/complete-server-test-es-module-migration)
> Migrate server locals tests to mocha

- src/browser/replay/recorder.js
> Fix private property typo

- src/browser/replay/defaults.js
- src/browser/replay/recorder.js
- test/browser.replay.recorder.test.js
This PR adds the `debug` options that were missed when implementing https://github.com/rollbar/rollbar.js/pull/1221.
This was causing the appropriate debugging logs not to show up even when these options were set to true.
A more appropriate solution may be in order in order to not having to keep track between adding/removing options from the defaults and having to remember to add/remove them from the source code as well.
> Missing debug was causing debug options to be ignored by the recorder

- src/browser/transport/fetch.js
- src/browser/transport/xhr.js
Only get replay related headers when the response is to an item request.
> Only extract replay headers in xhr and fetch when appropriate

- src/tracing/span.js
`Span.setAttribute` doesn't seem to be checking the correct `ended` attribute.
> Fixed span not checking correct ended prop when setting attributes

- src/tracing/tracer.js
Make Tracer pass `options.startTime` as is to the `Span` being created, similar to what the reference implementation does: https://github.com/open-telemetry/opentelemetry-js/blob/v2.0.1/packages/opentelemetry-sdk-trace-base/src/Tracer.ts#L68.
> Pass options.startTime to Span in Tracer

- src/browser/replay/recorder.js
- test/browser.replay.recorder.test.js
Helps the application correctly align playback by adding a noop event to the end of the recording.
> Send custom 'end' event

- .github/workflows/ci.yml
- package-lock.json
- package.json
- webpack.config.cjs
This PR fixes some ES5 transpilation issues:
1. rrweb ships modern JS (ES6+), we're now specifically transpiling this library and ignoring all the rest in `node_modules`.
2. rollbar.snippet.js stopped being transpiled to ES5 between version 2.26.3 and 2.26.4, a cursory look didn't bring anything in particular that should produce this, but [my #1 suspect is this PR](https://github.com/rollbar/rollbar.js/pull/1133)
On top of that, I've added [`es-check`](https://www.npmjs.com/package/es-check) as a dev dependency which allows us to do a proper compatibility check (via ast) of JS files. I integrated this to the CI, so any PR that may break ES5 in `/dist/` won't be able to be merged:
CI run for this PR:
```sh
Run npm run validate:es5
> rollbar@3.0.0-alpha.2 validate:es5
> es-check es5 …
```
> Fix non-ES5 dist bundles and add check to CI

- index.d.ts
- src/browser/replay/defaults.js
- src/browser/replay/recorder.js
- src/rollbar.js
- src/utility.js
- test/browser.replay.recorder.test.js
- test/browser.rollbar.test.js
Replaces `triggerOptions` with a minimal initial implementation of the `triggers` array, which can support multiple types of triggers with different configurations.
The default if no `triggers` key is present is, as before, an occurrence trigger on `error` and `critical` level.
This initial implementation allows users of the next alpha release to use the new config to modify or disable the occurrence trigger.
> Initial (minimal) support for replay triggers config

- examples/README.md
- package.json
- src/server/rollbar.cjs
This PR fixes more issues around `import` and `require` discrepancies by introducing a modern way to define package entry points, called [Conditional Exports](https://nodejs.org/api/packages.html#conditional-exports) which [were introduced 6 years ago in Node 12.7.0](https://nodejs.org/en/blog/release/v12.7.0).
Conditional Exports replace the legacy `main`, `browser` and `module` fields providing fine-grained control over what files can be imported from our package and how.
This change was prompted by the `universal-node` example which wouldn't be able to `require('rollbar')` without suffixing `.default` to it. This is because node looked into our `package.json` and resolved to use our `main` field which points to an es module.
> [!NOTE]
>  Before Conditional Exports, packages had to …
> Use package entry points for conditional exports between cjs/esm

- examples/README.md
Change the link for the `require` example for Node.js in the integration compatibility matrix in `examples/README.md`.
> Fix the Node.js require link in examples/README.md

- src/browser/bundles/defaults.js
Turns out, using concatenation results in a smaller minified file as the transpiler...
Turns this interpolated strings
```js
export const defaultRollbarJsUrl = 'https://${cdnHost}/rollbarjs/refs/tags/v${version}/rollbar.min.js`;
```
into
```js
var u="https://".concat("cdn.rollbar.com","/rollbarjs/refs/tags/v").concat("3.0.0-alpha.3","/rollbar.min.js");
```
While if we use concatenation, it turns
```js
export const defaultRollbarJsUrl = 'https://' + cdnHost + '/rollbarjs/refs/tags/v' + version + '/rollbar.min.js';
```
into a static string:
```js
"https://cdn.rollbar.com/rollbarjs/refs/tags/v3.0.0-alpha.3/rollbar.min.js"
```
This takes the size of `rollbar.snippet.js` back to its usual 6581 bytes.
> Use concatenation to build the cdn url for the browser snippet

- scripts/update-example-snippets.js
I found a bug in the new update snippets script that would occur after doing a `build:dev`. The resulting examples would contain the multiline rollbar snippet and on trying to build again using `build`, the regex wouldn't match because `.` wasn't matching multiple lines.
This fixes this problem.
> Fix bug when updating snippets after doing a dev build

- scripts/update-example-snippets.js
This pull request updates the `updateSnippets` function in `scripts/update-example-snippets.js` to improve file selection during snippet updates.
File selection improvement:
* Updated the `glob.sync` call in `updateSnippets` to ignore files in `.git` and `node_modules` directories, ensuring these are excluded from the snippet update process.
[SDK-506/replace-grunt-with-direct-tool-usage](https://linear.app/rollbar-inc/issue/SDK-506/replace-grunt-with-direct-tool-usage)
> Fixed update example snippets getting into .git and node_modules dirs

- .gitignore
- examples/react-19-typescript/package.json
- examples/react/package.json
- package-lock.json
Both react projects now point to a packed tgz file generated by `npm pack`. I'll automate this in an upcoming PR.
In order for it to work, simply:
```sh
$ npm install
$ npm run build
$ npm pack
$ mv rollbar-3.0.0-alpha.4.tgz ./.pack/rollbar.tgz
$ cd examples/react-19-typescript
$ rm -rf build node_modules/ package-lock.json # removing package-lock.json is necessary to prevent npm from using the old cached packed tarball
$ npm install
$ npm run build
```
> [!IMPORTANT]
> **Next PR:** The fix for the import issue with typescript.
[SDK-518/make-sure-all-sdk-examples-work-properly](https://linear.app/rollbar-inc/issue/SDK-518/make-sure-all-sdk-examples-work-properly)
> Have react and react ts projects point to npm packed release

- index.d.ts
- src/browser/core.d.ts
- src/browser/replay/recorder.d.ts
- src/browser/telemetry.d.ts
- src/browser/wrapGlobals.d.ts
- src/scrub.d.ts
- src/telemetry.d.ts
- src/tracing/tracing.d.ts
- src/truncation.d.ts
Our type def files hadn't been migrated to ES Modules, so they were causing trouble on typescript projects. This PR migrates all type defs to es mod.
[SDK-492/migrate-source-code-to-es-modules](https://linear.app/rollbar-inc/issue/SDK-492/migrate-source-code-to-es-modules)
> Migrated type def files from commonjs to es modules

- examples/angular/src/app/app.component.ts
- examples/angular/src/app/rollbar.errorhandler.ts
The Angular example was importing Rollbar as a namespace which was causing these errors during `npm run build`:
```ts
✘ [ERROR] TS2709: Cannot use namespace 'Rollbar' as a type. [plugin angular-compiler]
src/app/app.component.ts:17:27:
17 │   private rollbar = inject<Rollbar>(RollbarService);
╵                            ~~~~~~~
✘ [ERROR] TS2709: Cannot use namespace 'Rollbar' as a type. [plugin angular-compiler]
src/app/rollbar.errorhandler.ts:6:49:
6 │ export const RollbarService = new InjectionToken<Rollbar>('rollbar');
╵                                                  ~~~~~~~
```
It's not recommended to import Rollbar as a namespace:
https://docs.rollbar.com/docs/importing-or-requiring-rollbar#namespace-import-syntax-not-recommended …
> Don't import Rollbar as a namespace in the Angular example

- src/browser/core.js
Sets the default environment to "unknown" to match 2.x rollbar.js.
> Set default environment to 'unknown'

- .github/workflows/ci.yml
- src/browser/telemetry.js
* Converts Instrumeter prototype functions to clas syntax.
* Removes some IE11 code.
* Converts some for loops to for ... in.
* Converts var to const/let.
> Convert Instrumenter to a class

- src/browser/domUtility.js
- src/browser/telemetry.js
- src/telemetry.js
- test/browser.telemetry.test.js
- test/fixtures/html/dom-events.html
Enables telemetry events for DOM events
* Input
* Click
* Focus
* Resize
And updates the connectivity event.
> Telemetry: enable dom events

- src/browser/replay/recorder.js
- src/browser/replay/replayManager.js
- src/telemetry.js
- src/tracing/session.js
Users upgrading to v3.0.0-beta.2 encountered build failures with the following error:
```
SyntaxError: Class private methods are not enabled. Please add `@babel/plugin-transform-private-methods` to your configuration.
```
This occurred when bundlers (like Next.js, Vite, or custom Webpack configs) attempted to process our source files that contained *ES2022* private class fields and methods (`#privateField`).
Since our SDK transpiles *ES2021* into *ES5* for broad compatibility, we cannot use syntax that requires additional Babel plugins that users may not have configured.
This PR replaces all private class syntax (`#`) with the underscore convention (`_`) to maintain backward compatibility while preserving the intended encapsulation pattern.
- Slack thread 1: …
> Change all octothorpes # to _ since private # is only >=ES2022

- src/browser/replay/defaults.js
- src/browser/replay/recorder.js
- src/browser/replay/replayManager.js
- test/browser.replay.recorder.test.js
- test/replay/unit/replayManager.test.js
> [!NOTE]
> PR Description by Copilot.
This pull request introduces support for "leading replay" capture in addition to the existing "trailing replay" functionality. Leading replay allows capturing and sending a short window of user events that occur after an error is triggered, improving the context available for debugging. The changes include new configuration options, enhancements to the replay recording and management logic, and additional state tracking for coordinating leading and trailing replay sends.
**Leading replay capture and coordination:**
* Added a new `postDuration` option to `defaults.js` to specify the number of seconds of events to capture after an error is triggered.
* Updated `ReplayManager` (`replayManager.js`) to schedule and export leading replay events after the …
> Capture leading replay

- src/browser/replay/replayManager.js
- src/queue.js
- test/replay/integration/queue.replayManager.test.js
- test/replay/integration/replayManager.test.js
- test/replay/integration/sessionRecording.test.js
- test/replay/unit/queue.replayManager.test.js
- test/replay/unit/replayManager.test.js
> [!NOTE]
> PR Description written by Copilot
This PR refactors the replay handling logic by moving responsibility for deciding whether to send or discard replays from the `Queue` class to the `ReplayManager` class. This centralization improves maintainability and separation of concerns.
- Added a new `sendOrDiscardReplay` method to `ReplayManager` that consolidates replay eligibility checks and error handling
- Updated `Queue` to delegate replay handling to `ReplayManager.sendOrDiscardReplay` instead of handling the logic internally
- Comprehensively updated all test suites to reflect the new integration point and method signatures
**Refactoring and Responsibility Shift:**
* Moved the replay eligibility check and send/discard logic from `Queue._sendOrDiscardReplay` and `_canSendReplay` …
> Move send replay from Queue to ReplayManager

- src/browser/replay/replayManager.js
- src/utility.js
- test/replay/integration/e2e.test.js
- test/replay/integration/replayManager.bufferIndex.checkoutResilience.test.js
- test/replay/integration/replayManager.bufferIndex.test.js
- test/replay/integration/replayManager.test.js
- test/replay/unit/replayManager.test.js
Adds the `rollbar.replay.url.full` attribute.
> Add rollbar.replay.url.full attribute
